var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).i}},"es6","es3");$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
$jscomp.polyfill("Math.trunc",function(a){return a?a:function(a){a=Number(a);if(isNaN(a)||Infinity===a||-Infinity===a||0===a)return a;var b=Math.floor(Math.abs(a));return 0>a?-b:b}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,d,e){return c==a&&"q"==d&&e==b}}));return!0===b.q}catch(c){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(h){return!1}}function c(){}function d(a){if(!$jscomp.owns(a,f)){var b=new c;$jscomp.defineProperty(a,f,{value:b})}}function e(a){var b=Object[a];b&&(Object[a]=function(a){if(a instanceof c)return a;d(a);return b(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&
$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,k=function(a){this.id_=(l+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};k.prototype.set=function(a,b){d(a);if(!$jscomp.owns(a,f))throw Error("WeakMap key fail: "+a);a[f][this.id_]=b;return this};k.prototype.get=function(a){return $jscomp.owns(a,f)?a[f][this.id_]:void 0};k.prototype.has=
function(a){return $jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)};k.prototype.delete=function(a){return $jscomp.owns(a,f)&&$jscomp.owns(a[f],this.id_)?delete a[f][this.id_]:!1};return k},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(m){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var c=new WeakMap,d=function(a){this.data_={};this.head_=l();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};d.prototype.set=function(a,b){a=0===a?0:a;var c=e(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=b:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};d.prototype.delete=function(a){a=e(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=l();this.size=0};d.prototype.has=function(a){return!!e(this,a).entry};
d.prototype.get=function(a){return(a=e(this,a).entry)&&a.value};d.prototype.entries=function(){return f(this,function(a){return[a.key,a.value]})};d.prototype.keys=function(){return f(this,function(a){return a.key})};d.prototype.values=function(){return f(this,function(a){return a.value})};d.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(a,b){var d=b&&typeof b;"object"==
d||"function"==d?c.has(b)?d=c.get(b):(d=""+ ++k,c.set(b,d)):d="p_"+b;var e=a.data_[d];if(e&&$jscomp.owns(a.data_,d))for(a=0;a<e.length;a++){var f=e[a];if(b!==b&&f.key!==f.key||b===f.key)return{id:d,list:e,index:a,entry:f}}return{id:d,list:e,index:-1,entry:void 0}},f=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},l=function(){var a={};return a.previous=
a.next=a.head=a},k=0;return d},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([b]));if(!c.has(b)||1!=c.size||c.add(b)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var f=c.entries(),l=f.next();if(l.done||l.value[0]!=b||l.value[1]!=b)return!1;l=f.next();return l.done||l.value[0]==b||4!=l.value[0].x||l.value[1]!=l.value[0]?!1:f.next().done}catch(k){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var c=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};c.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};c.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};c.prototype.clear=function(){this.map_.clear();
this.size=0};c.prototype.has=function(a){return this.map_.has(a)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};return c},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6","es3");function ga(a,b,c,d){}
(function(a,b,c,d,e){a.GoogleAnalyticsObject=e;a[e]=a[e]||function(){(a[e].q=a[e].q||[]).push(arguments)};a[e].l=1*new Date;var f=b.createElement(c);b=b.getElementsByTagName(c)[0];f.async=1;f.src=d;b.parentNode.insertBefore(f,b)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create","UA-96461430-1","auto");ga("send","pageview");var app_config={test_percent_cap:100,chunk:300,useCredentials:!1,URLprefix:"https://stevens-scheduler.cfapps.io/p/"},GETPOST;app_config.URLgetTerms=function(a){a.openMethod="GET";a.url=app_config.URLprefix+"terms"};app_config.URLgetCourses=function(a,b,c,d){a.openMethod="GET";a.url=app_config.URLprefix+b};app_config.URLgetDescription=function(a,b,c){a.openMethod="GET";a.url=app_config.URLprefix+"desc/"+c};app_config.URLgetCourseTotalCount=function(a,b){a.url=""};
app_config.URLtest=function(a){a.openMethod="GET";a.url="https://stevens-scheduler.cfapps.io/"};app_config.URLprime=function(a,b){a.openMethod="GET";a.url=""};var Term;
app_config.PROCESSgetTerms=function(a){var b=[];JSON.parse(a).forEach(function(a){var c=a.substr(0,4),e=a.substr(4);c+=" ";switch(e){case "S":c+="Spring";break;case "F":c+="Fall";break;case "A":c+="Summer I";break;case "B":c+="Summer II";break;case "W":c+="Winter";break;default:c+="undefined"}b.push({URLcode:a,title:c+(" ("+a+")")})});return b};app_config.PROCESSgetCourseTotalCount=function(a){return 1};var Meeting,Course;
Date.prototype.stdTimezoneOffset=function(){var a=new Date(this.getFullYear(),0,1),b=new Date(this.getFullYear(),6,1);return Math.max(a.getTimezoneOffset(),b.getTimezoneOffset())};Date.prototype.isDstObserved=function(){return this.getTimezoneOffset()<this.stdTimezoneOffset()};
app_config.PROCESSgetCourses=function(a){a=JSON.parse(a);var b=[],c=new Date;a.forEach(function(a){var d={};try{d.courseNumber=a.section.match(/\d+/g)[0];d.subject=a.section.match(/[a-zA-Z]+/g)[0];d.sessionMod=a.section.match(/[a-zA-Z]+/g)[1];d.courseRegistrationCode=a.callNumber;d.title=a.title;d.URLcode=d.courseRegistrationCode;d.GETcode=d.subject+" "+d.courseNumber+d.sessionMod;d.credits=a.credits;d.faculty=a.instructor;var f=a.section.match(/[a-zA-Z]+/g)[1];d.scheduleTypeDescription=1>=f.length?
"Lecture":f[0];d.maximumEnrollment=parseInt(a.maxEnrollment,10);d.seatsAvailable=a.seatsAvailable?parseInt(a.seatsAvailable,10):d.maximumEnrollment-parseInt(a.currentEnrollment,10);d.meetings=a.daysTimeLocation.filter(function(a){return void 0!=a.startTime&&void 0!=a.endTime}).map(function(a){if("WS"==a.site||"WEB"==a.room)return d.scheduleTypeDescription="L",{building:"ONLINE",room:"ONLINE",monday:!1,tuesday:!1,wednesday:!1,thursday:!1,friday:!1,saturday:!1,sunday:!1};if("TBA"!=a.day){var b={building:a.building,
room:a.room,monday:a.day.includes("M"),tuesday:a.day.includes("T"),wednesday:a.day.includes("W"),thursday:a.day.includes("R"),friday:a.day.includes("F"),saturday:!1,sunday:!1};b.beginTime=a.startTime.substr(0,a.startTime.length-4).split(":");b.beginTime=b.beginTime.join("");b.endTime=a.endTime.substr(0,a.endTime.length-4).split(":");b.endTime=b.endTime.join("");b.beginTime=(parseInt(b.beginTime,10)+400+100*!c.isDstObserved()).toString();b.endTime=(parseInt(b.endTime,10)+400+100*!c.isDstObserved()).toString();
return b}}).filter(function(a){return void 0!==a});b.push(d)}catch(l){console.error("Something's wrong with a course. Ignoring: ",d)}});return b.map(function(a){"S"==a.scheduleTypeDescription&&(a.scheduleTypeDescription=a.sessionMod.substr(1)[0]||"");return a})};app_config.PROCESSgetDescription=function(a){for(a=a.replace(/<br>/g,"\r\n").replace(/<BR>/g,"\r\n").trim();"\r\n"==a.substr(0,2);)a=a.substr(2,a.length);for(;"\r\n"==a.substr(a.length-2,a.length-1);)a=a.substr(0,a.length-2);return a};
app_config.collegeName="Stevens Institute of Technology";app_config.collegeNameShort="SIT";app_config.siteTitle="SIT Scheduler - Course Scheduler for Stevens Institute of Technology";app_config.siteTitleShort="SIT Scheduler";app_config.courseRegistrationCodeName="CN";app_config.getLogoName=function(a){return"Stevens-Official-"+(a?"WhiteKO":"PMSColor")+"-R.svg"};app_config.CORStest=!1;app_config.CORScustom="";document.title=app_config.siteTitle;
!0===app_config.CORStest?document.getElementById("cors").innerHTML="Hi, and welcome to "+app_config.siteTitleShort+"! This is a tool for creating, editing, testing, and sharing schedules for "+app_config.collegeName+".<br><br>I can see you're locked out of the "+app_config.collegeNameShort+" systems. Unfortunately, there isn't anything the developer can do about this problem. This is because "+app_config.collegeNameShort+" won't recognize this website as friendly.<br><b>In order to use this tool, please download and use a CORS-everywhere extension</b> and refresh. This intercepts data coming from "+app_config.collegeNameShort+
"'s servers and makes your browser think "+app_config.collegeNameShort+' trusts us, so that your browser doesn\'t lock you out. Here are a few I recommend:<br><a href="https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/">Firefox</a><br>For Chrome, it\'s a bit more envolved. See <a href="https://www.codevoila.com/post/75/how-to-disable-same-origin-policy-in-chrome">this</a> for more details.<br>NOTE: it is technically unsafe to browse with CORS-everywhere enabled. Please, disable it when not using this tool.<br><br><b>'+
app_config.CORScustom+"</b>":document.getElementById("cors").innerHTML="Hi, and welcome to "+app_config.siteTitleShort+"! This is a tool for creating, editing, testing, and sharing schedules for "+app_config.collegeName+".<br><br><b>The "+app_config.collegeNameShort+" servers seem to be down right now. Check back later.</b><br><br>If you're a developer, this might be a CORS related issue.";
(function(){for(var a=document.getElementById("schedThead"),b="Monday Tuesday Wednesday Thursday Friday Saturday Sunday".split(" "),c=0;c<b.length;++c){var d=b[c],e=document.createElement("th");e.innerText=d;a.appendChild(e)}})();
(function(){var a=document.getElementById("schedTbody"),b=[8,9,10,11,12,13,14,15,16,17,18,19,20],c="monday tuesday wednesday thursday friday saturday sunday".split(" "),d=document.createElement("tr"),e=document.createElement("td");e.className="time";d.appendChild(e);e=document.createElement("td");e.className="block";var f=document.createElement("div");f.className="wrapper";var l=document.createElement("div");l.className="wrapperInternal";f.appendChild(l);f.appendChild(document.createElement("div"));
f.appendChild(document.createElement("div"));e.appendChild(f);for(f=0;f<b.length;++f){l=b[f];var k=d.cloneNode(!0);k.firstChild.innerText=(l-1)%12+1+":00";for(var g=0;g<c.length;++g){var n=c[g],p=e.cloneNode(!0);p.firstChild.firstChild.setAttribute("data-hour",l);p.firstChild.firstChild.setAttribute("data-day",n);k.appendChild(p)}a.appendChild(k)}})();
(function(){var a=document.getElementById("schedThead").children;a[6].style.display="none";a[7].style.display="none";a=document.getElementById("schedTbody").children;for(var b=0;b<a.length;++b)a[b].children[6].style.display="none",a[b].children[7].style.display="none"})();window.onresize=function(){var a=document.getElementById("weekTableWrapper");document.getElementById("weekTableHead").style.borderRight=(a.offsetWidth-a.clientWidth).toString()+"px solid "+getComputedStyle(document.getElementById("schedThead")).backgroundColor};var postProcessCourses=function(a){return a.filter(function(a){return a.meetings.reduce(function(a,b){return a||"monday tuesday wednesday thursday friday saturday sunday".split(" ").reduce(function(a,c){return a||b[c]},!1)||"ONLINE"==b.building},!1)}).map(function(a){a.scheduleTypeDescription.includes("Honors ")&&(a.scheduleTypeDescription=a.scheduleTypeDescription.split("Honors ")[1]);return a}).reduce(function(a,c){return 0<a.length?(a[a.length-1][0].subject+a[a.length-1][0].courseNumber==c.subject+
c.courseNumber?a[a.length-1].push(c):a.push([c]),a):[[c]]},[]).map(function(a){a[0].home=a[0];a[0].alts=[[a[0]]];for(var b=1;b<a.length;++b){a[b].home=a[0];var d=a[0].alts.findIndex(function(c){return c[0].scheduleTypeDescription==a[b].scheduleTypeDescription});-1<d?a[0].alts[d].push(a[b]):a[0].alts.push([a[b]])}return a}).reduce(function(a,c){return a.concat(c)},[]).map(function(a,c){a.index=c;return a})},Searcher=function(a,b,c,d){this.term=void 0===b?"":b;this.data=[];this.done=!1;this.offset=
void 0===c?"":c;this.size=void 0===d?0:d;this.xhr=null;this.type=a};
Searcher.prototype.start=function(a,b){a=void 0===a?null:a;b=void 0===b?null:b;if(!this.xhr&&!this.done){var c={postData:"0",openMethod:"",url:""};switch(this.type){case "prime":app_config.URLprime(c,this.term);break;case "count":app_config.URLgetCourseTotalCount(c,this.term);break;case "courses":app_config.URLgetCourses(c,this.term,this.offset.toString(),this.size);break;case "terms":app_config.URLgetTerms(c);break;case "desc":app_config.URLgetDescription(c,this.term,this.offset.toString());break;
case "test":app_config.URLtest(c);break;default:console.error("Invalid type in Searcher")}if(""==c.url){if("prime"==this.type||"count"==this.type){this.xhr=null;this.done=!0;a(!1);return}console.error("url not set for request of type "+this.type+". There's an erorr in config.js")}""==c.openMethod&&console.error("openMethod not set for request of type "+this.type+". There's an erorr in config.js");"POST"==c.openMethod&&"0"==c.postData&&console.error("postData is missing for POST request of type "+
this.type+". There's an erorr in config.js");this.xhr=new XMLHttpRequest;this.xhr.onreadystatechange=function(c){return function(){4==this.readyState&&(this.done=!0,c.xhr=null);"test"==c.type&&4===this.readyState&&0===this.status?(!0===app_config.CORStest?console.error("CORS DENIED - please enable a CORS-everywhere extension or ask "+app_config.collegeNameShort+" to let us in"):console.error("Can't communicate with "+app_config.collegeName+" servers. They're probable down right now - check back later."),
a&&a(!1)):"test"==c.type&&4===this.readyState?a&&a(!0):"test"!=c.type&&(4===this.readyState&&200===this.status?(a&&a(this.responseText),c.done=!0,c.xhr=null):200!=this.status&&4==this.readyState&&(b?b(this.status,this.responseText):console.error("Unhandled erorr on HTTP request: ",this.status.toString())))}}(this);this.xhr.open(c.openMethod,c.url);this.xhr.withCredentials=app_config.useCredentials;"POST"==c.openMethod&&this.xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
this.xhr.send(c.postData)}};Searcher.prototype.stop=function(){this.xhr&&!this.done&&(this.xhr.abort(),this.xhr=null)};var TermManager=function(a){this.term=a;this.data=[];this.done=!1;this.requests=[];this.headRequest=null;this.main_callback_wrapper={callback:null};this.totalCount=0};
TermManager.prototype.start=function(a,b){b=void 0===b?!1:b;this.main_callback_wrapper.callback=a;this.done?a&&a(this.data):this.headRequest||(a=function(a){return function(b){a.requests.length?(b=a.data.reduce(function(a,b){return a+b.courses.length},0),0!==a.totalCount&&(app.percent=b.toString()+"/"+a.totalCount.toString(),app.updatePercent()),a.headRequest=null,a.requests.forEach(function(b){b.start(function(c){c=app_config.PROCESSgetCourses(c);a.data.push({courses:c,offset:b.offset});c=a.data.reduce(function(a,
b){return a+b.courses.length},0);0!==a.totalCount&&(app.percent=c.toString()+"/"+a.totalCount.toString(),app.updatePercent());if(0===a.totalCount||c>=app_config.test_percent_cap*a.totalCount/100){app.percent+="\nProcessng courses...";app.updatePercent();a.data=postProcessCourses(a.data.sort(function(a,b){return a.offset-b.offset}).reduce(function(a,b){return a.concat(b.courses)},[]));a.done=!0;a.requests=[];a.main_callback_wrapper.callback&&a.main_callback_wrapper.callback(a.data);c=document.getElementById("saves").children;
for(var d=[],e=0;e<c.length;++e)d.push(JSON.parse(window.localStorage.schedules)[c[e].innerText].split("=")[0]);c=app.termCacher.termManagers.filter(function(a){return a.done}).map(function(a){return a.term});for(e=0;e<d.length;++e)if(!c.find(function(a){return a==d[e]})){app.termCacher.push(d[e],null);break}}},function(a,b){404==a&&("Cache not warm"==b?alert("It looks like the server just started recently and has not downloaded data for this term yet. Please try again in a few minutes."):""!==b&&
console.error("Unhandled error "+a+":"+b))})})):(app.percent="0/?",app.updatePercent(),a.headRequest=new Searcher("count",a.term),a.headRequest.start(function(b){a.headRequest=null;if(!1===b)app.percent="",app.updatePercent(),b=new Searcher("courses",a.term,"0",0),b.offset=0,a.requests.push(b);else{a.totalCount=app_config.PROCESSgetCourseTotalCount(b);app.percent="0/"+a.totalCount.toString();app.updatePercent();b=[];for(var c=0;c<app_config.test_percent_cap*a.totalCount/100;c+=app_config.chunk)b.push(c);
b.forEach(function(b){var c=new Searcher("courses",a.term,b,app_config.chunk);c.offset=b;a.requests.push(c)})}a.start(a.main_callback_wrapper.callback,!0)}))}}(this),b?a(null):(this.headRequest=new Searcher("prime",this.term),this.headRequest.start(a)))};TermManager.prototype.stop=function(){this.done||(this.main_callback_wrapper.callback=null,this.headRequest&&(this.headRequest.stop(),this.headRequest=null),this.requests.forEach(function(a){a.stop()}))};
var TermCacher=function(){this.termManagers=[]};
TermCacher.prototype.push=function(a,b){b=void 0===b?null:b;var c=this.termManagers.findIndex(function(b){return b.term==a});if(-1<c&&this.termManagers[c].done)this.termManagers.forEach(function(a){a.main_callback_wrapper.callback=null}),this.termManagers[c].start(b);else{var d=null;-1<c&&(d=this.termManagers.splice(c,1)[0]);this.termManagers.forEach(function(a){a.stop()});this.termManagers.push(-1<c?d:new TermManager(a));this.termManagers[this.termManagers.length-1].start(b)}};var app={course:null,courses:[],selected:[],mode:"Manual",courses_generator:null,savedCourseGenerator:"0",course_list_selection:0,hovering:[],currentstorage:null,terms:[],term:"",courses_auto:"",courses_manual:"",closed:!1,percent:""};app.termCacher=new TermCacher;app.generateHash=function(a){var b=app.term+"=",c=app.selected;"Automatic"===app.mode&&app.courses_generator&&app.courses_generator.data&&app.courses_generator.data[app.course_list_selection]&&(c=app.courses_generator.data[app.course_list_selection].selected);b+=c.sort(function(a,b){return a.URLcode-b.URLcode}).map(function(a){return a.URLcode+(a.locked?"!":"")}).join();app.closed&&(b+="&C");!0===a&&(b+="+"+document.getElementById("notes").value);return b};app.getHash=function(){return decodeURIComponent(location.hash)};
app.changed=function(){if(0==app.selected.length)return!1;for(var a=document.getElementById("saves").children,b=!0,c=-1,d=0;d<a.length;++d)a[d].classList.contains("selected")&&(c=d);if(-1<c)b=JSON.parse(window.localStorage.schedules)[a[c].innerText]!=app.generateHash(!0);else for(d=0;d<a.length;++d)a[d].classList.contains("preselect")&&(b=JSON.parse(window.localStorage.schedules)[a[d].innerText]!=app.generateHash(!0));return b};
app.autoInAlts=function(a,b){return null==a||null==b?!1:"Manual"==app.mode?a==b:a.home==b.home};window.addEventListener("keydown",function(a){"Escape"==a.key&&(document.getElementById("selectBox").value="",app.course=null,app.savedCourseGenerator="",app.courses_generator=null,app.fillSchedule())});var change_style=function(a){for(var b=0;b<document.styleSheets.length;++b)document.styleSheets[b].href.includes("style_dark.min.css")&&(document.styleSheets[b].disabled=!a.checked);document.getElementById("logo").src=app_config.getLogoName(a.checked);window.localStorage.darkMode=a.checked.toString()};
app.autoAndLabs=function(a){return null==a?[]:"Manual"==app.mode?[a]:app.courses_generator?app.courses_generator.get(app.course_list_selection).filter(function(b){return b&&b.home==a.home}):[]};
app.fillSchedule=function(a){if(a=void 0===a?null:a)app.course_list_selection=a.value;app.course=""!=document.getElementById("selectBox").value?parseInt(document.getElementById("selectBox").value,10):null;var b=document.getElementsByClassName("wrapperInternal"),c=app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null),!0).get("Manual"==app.mode?0:app.course_list_selection);a=[];for(var d=0;d<b.length;++d){for(var e=b[d],f=e.getAttribute("data-day"),l=e.getAttribute("data-hour");e.firstChild;)e.removeChild(e.firstChild);
for(var k=0;k<c.length;++k){var g=c[k],n=app.courseHere(f,l,g);if(g&&n){var p=document.createElement("div");if("Automatic"==app.mode||!app.autoInAlts(g,null!==app.course?app.courses[app.course]:null)){var h=document.createElement("div");h.className="autoLock";h.innerText=g.locked?"\ud83d\udd12":"\ud83d\udd13 ";h.onclick=function(a,b){return function(b){app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection,!0);a.locked=!a.locked;app.savedCourseGenerator=
"";app.fillSchedule();null===app.course||app.autoInAlts(app.courses[app.course],a)||(location.hash=app.generateHash(!1))}}(g,h);h.style.top=100*n.top+"%";p.appendChild(h)}h=document.createElement("div");h.className="item";var m=g.subject+" "+g.courseNumber+"\n"+g.title.replace(/&ndash;/g,"\u2013")+"\n"+(g.faculty.trim().length?g.faculty+"\n":"")+(n.loc.length?n.loc+"\n":"")+g.credits+" credit"+(1!=g.credits?"s":"")+"\n";void 0!==g.seatsAvailable&&void 0!==g.maximumEnrollment&&(m+=Math.max(0,g.seatsAvailable)+
"/"+g.maximumEnrollment+" seats open\n");void 0!==g.waitAvailable&&void 0!==g.waitAvailable&&(m+=g.waitAvailable+"/"+g.waitCapacity+" waitlist open\n");m+=app_config.courseRegistrationCodeName+": "+g.courseRegistrationCode+"\n";h.innerText=m;m=document.createElement("a");m.className="link";m.onclick=function(a){return function(){app.fetchDescription(a)}}(g);m.innerText="Description";h.appendChild(m);h.setAttribute("data-index",g.index);h.setAttribute("data-length",n.length);h.setAttribute("data-top",
n.top);app.autoInAlts(g,null!==app.course?app.courses[app.course]:null)||h.classList.add("selected");h.style.top=100*h.getAttribute("data-top")+"%";h.style.height=app.hovering.includes(g)?"auto":100*h.getAttribute("data-length")+"%";h.style.minHeight=app.hovering.includes(g)?100*h.getAttribute("data-length")+"%":"auto";!app.closed&&"Manual"==app.mode&&!g.locked&&0>=g.seatsAvailable&&(g=document.createElement("div"),g.className="closedAlign",n=document.createElement("div"),n.className="closedMsg",
n.innerText="CLOSED",g.appendChild(n),h.insertBefore(g,h.childNodes[0]));p.appendChild(h);e.appendChild(p);a.push(h)}}}k=document.getElementById("webWrapper");for(b=document.getElementById("web");b.firstChild;)b.removeChild(b.firstChild);c=Array.isArray(c)?app.webclasses(c):[];k.style.display=c.length?"":"none";for(k=0;k<c.length;++k)if(g=c[k])p=document.createElement("div"),"Automatic"!=app.mode&&app.autoInAlts(g,null!==app.course?app.courses[app.course]:null)||(h=document.createElement("div"),h.className=
"autoLock",h.innerText=g.locked?"\ud83d\udd12":"\ud83d\udd13 ",h.onclick=function(a){return function(b){app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection,!0);a.locked=!a.locked;app.savedCourseGenerator="";app.fillSchedule();null===app.course||app.autoInAlts(app.courses[app.course],a)||(location.hash=app.generateHash(!1))}}(g),p.appendChild(h)),h=document.createElement("div"),h.className="item",m=g.subject+" "+g.courseNumber+"\n"+g.title.replace(/&ndash;/g,
"\u2013")+"\n"+(g.faculty.trim().length?g.faculty+"\n":"")+g.credits+" credit"+(1!=g.credits?"s":"")+"\n",void 0!==g.seatsAvailable&&void 0!==g.maximumEnrollment&&(m+=Math.max(0,g.seatsAvailable)+"/"+g.maximumEnrollment+" seats open\n"),void 0!==g.waitAvailable&&void 0!==g.waitAvailable&&(m+=g.waitAvailable+"/"+g.waitCapacity+" waitlist open\n"),m+=app_config.courseRegistrationCodeName+": "+g.courseRegistrationCode+"\n",h.innerText=m,m=document.createElement("a"),m.className="link",m.onclick=function(a){return function(){app.fetchDescription(a)}}(g),
m.innerText="Description",h.appendChild(m),h.setAttribute("data-index",g.index),app.autoInAlts(g,null!==app.course?app.courses[app.course]:null)||h.classList.add("selected"),p.appendChild(h),!app.closed&&"Manual"==app.mode&&!g.locked&&0>=g.seatsAvailable&&(d=document.createElement("div"),d.className="closedAlign",e=document.createElement("div"),e.className="closedMsg",e.innerText="CLOSED",d.appendChild(e),h.insertBefore(d,h.childNodes[0])),b.appendChild(p),a.push(h);var q=function(a){return function(){for(var b=
0;b<a.length;++b){var c=a[b],d=app.courses[c.getAttribute("data-index")];app.autoInAlts(d,null!==app.course?app.courses[app.course]:null)?c.classList.remove("selected"):c.classList.add("selected");var e=c.parentElement.getElementsByClassName("autoLock");null!==d&&app.hovering.includes(d)?(e.length&&e[0].classList.add("hovering"),c.classList.add("hovering")):(e.length&&e[0].classList.remove("hovering"),c.classList.remove("hovering"));c.getAttribute("data-top")&&(c.style.top=100*c.getAttribute("data-top")+
"%",c.style.height=null!==d&&app.hovering.includes(d)?"auto":100*c.getAttribute("data-length")+"%",c.style.minHeight=null!==d&&app.hovering.includes(d)?100*c.getAttribute("data-length")+"%":"auto")}}}(a);q();for(k=0;k<a.length;++k)a[k].ondblclick=function(a){return function(){app.click(a);app.course=null;document.getElementById("selectBox").value=""}}(app.courses[a[k].getAttribute("data-index")]),a[k].parentElement.onmouseover=function(a){return function(){app.hovering=app.autoAndLabs(a);q()}}(app.courses[a[k].getAttribute("data-index")]),
a[k].parentElement.onmouseout=function(){return function(){app.hovering=[];q()}}();app.dayUpdate();app.autoBar();app.saveMarker();app.updateCredits();document.getElementById("escTip").style.display=null!=app.course?"":"none";window.localStorage.setItem("lastViewed",app.generateHash(!1))};app.disableOnHashChange=!1;
window.onhashchange=function(){app.disableOnHashChange||app.generateHash(!1)==app.getHash().substr(1)||(app.getHash().substr(1).split("=")[0].length?(app.changedTerm("first",{value:app.terms[app.terms.map(function(a){return a.URLcode}).indexOf(app.getHash().split("=")[0].substr(1))].URLcode}),app.updateTerms()):app.clear());app.disableOnHashChange=!1};
app.courseHere=function(a,b,c){if(!c)return null;var d=parseInt(b,10),e=null;c.meetings.forEach(function(b){if("WS"!=b.building&&b.beginTime&&b[a]){var c=app.convertTime(b.beginTime),f=app.convertTime(b.endTime);Math.trunc(c)==d-8&&(e={top:c-Math.trunc(c),length:f-c,loc:b.building&&b.building.trim().length&&b.room&&b.room.trim().length?b.building+" "+b.room:""})}});return e};app.convertTime=function(a){var b=a.substr(-2);return parseFloat(a.substr(0,a.length-b.length))+parseFloat(b)/60-8};
app.webclasses=function(a){return a?a.filter(function(a){return a&&a.meetings.map(function(a){return"ONLINE"==a.building}).reduce(function(a,b){return a||b},!1)}):[]};
app.fetchDescription=function(a){ga("send","event","description","fetch");document.getElementById("description-fetch").style.display="";document.getElementById("description-show").style.display="none";document.getElementById("description").style.display="";document.getElementById("description-strong").innerText=a.subject+" "+a.courseNumber+":";var b=function(a){var b=document.getElementById("description-show");b.innerText=a;b.style.display="";document.getElementById("description-fetch").style.display=
"none"};a.description?b(a.description):(new Searcher("desc",app.term.toString(),a.GETcode.toString())).start(function(c){c=app_config.PROCESSgetDescription(c);b(c);a.description=c})};
app.dayUpdate=function(){if("Automatic"==app.mode)0==app.selected.length||app.courses_generator&&app.courses_generator.data&&app.courses_generator.data[app.course_list_selection]?document.getElementById("noSchedWrapper").style.display="none":document.getElementById("noSchedWrapper").style.display="";else if(document.getElementById("noSchedWrapper").style.display="none","none"==document.getElementById("schedTbody").children[0].children[1].style.display)for(var a=1;5>=a;++a)for(var b=document.getElementById("schedTbody").children,
c=0;c<b.length;++c)b[c].children[a].style.display="";if(0<(null===app.course?app.selected:app.selected.concat(app.courses[app.course])).filter(function(a){return 0<a.meetings.filter(function(a){return a.saturday||a.sunday}).length}).length)for(document.getElementById("schedThead").children[6].style.display="",b=document.getElementById("schedTbody").children,a=0;a<b.length;++a)b[a].children[6].style.display="";else for(document.getElementById("schedThead").children[6].style.display="none",b=document.getElementById("schedTbody").children,
a=0;a<b.length;++a)b[a].children[6].style.display="none";if(0<(null===app.course?app.selected:app.selected.concat(app.courses[app.course])).filter(function(a){return 0<a.meetings.filter(function(a){return a.sunday}).length}).length)for(document.getElementById("schedThead").children[7].style.display="",b=document.getElementById("schedTbody").children,a=0;a<b.length;++a)b[a].children[7].style.display="";else for(document.getElementById("schedThead").children[7].style.display="none",b=document.getElementById("schedTbody").children,
a=0;a<b.length;++a)b[a].children[7].style.display="none"};
app.loadHash=function(a){a=void 0===a?!1:a;if(app.getHash().split("=")[0].length){var b=app.getHash().split("=")[1].split("&")[0].split(",");app.selected=app.courses.filter(function(a){var c=b.map(function(a){return a.replace("!","")}).indexOf(a.URLcode.toString());-1<c&&(a.locked="!"==b[c][b[c].length-1]);return-1<c});document.getElementById("closedCheck").checked=!!app.getHash().split("&")[1];app.closed=!!app.getHash().split("&")[1];if(a){a=[];for(var c=0,d=document.getElementById("saves").children;c<
d.length;++c)JSON.parse(window.localStorage.schedules)[d[c].innerText].split("+")[0]==app.getHash().split("#")[1]&&a.push(d[c]);c=a.filter(function(a){return JSON.parse(window.localStorage.schedules)[a.innerText].split("+")[0]+"?"+a.innerText==window.localStorage.lastSaved});a.length&&((c.length?c[0]:a[0]).classList.add("selected"),app.currentstorage=(c.length?c[0]:a[0]).innerText,document.getElementById("notes").value=JSON.parse(window.localStorage.schedules)[app.currentstorage].split("+")[1])}}else app.clear()};
app.click=function(a){if(null!==a){if(app.autoInAlts(null!==app.course?app.courses[app.course]:null,a))if(ga("send","event","course","add"),document.getElementById("selectBox").value="","Manual"==app.mode)app.course=null,app.selected.push(a);else{var b=app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection).filter(function(a){return app.autoInAlts(null!==app.course?app.courses[app.course]:null,a)});app.course=null;b.forEach(function(a){return app.selected.push(a)});
app.savedCourseGenerator="A";app.autoConstruct(app.selected).get(app.course_list_selection,!0)}else{ga("send","event","course","remove");if("Manual"==app.mode)a.locked=!1,app.selected.splice(app.selected.indexOf(a),1);else{b=app.selected.filter(function(b){return a.home==b.home});for(var c=0;c<b.length;++c)b[c].locked=!1;app.selected=app.selected.filter(function(b){return a.home!=b.home})}app.hovering=[]}location.hash=app.generateHash(!1);app.course_list_selection=0;b=document.getElementById("Range");
b.max=0;b.value=0;app.hideSearch();app.fillSchedule()}};app.totalCredits=function(){return app.selected.reduce(function(a,b){return a+b.credits},0)};app.updateCredits=function(){document.getElementById("credits").innerText=app.totalCredits()};
app.autoBar=function(){var a=document.getElementById("autoBar");a.style.display="Automatic"==app.mode&&(0<app.selected.length||null!==app.course)&&app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(1,!1)?"block":"none";document.getElementById("nextButton").innerText="Next";"none"==a.style.display?(document.getElementById("selectBox").size=25,document.getElementById("Automatic").style.marginBottom="10px"):(document.getElementById("selectBox").size=24,document.getElementById("Automatic").style.marginBottom=
"0px")};
app.genNext=function(a){if(a){app.courses_generator&&app.courses_generator.get(app.courses_generator.data?app.courses_generator.data.length:0)?app.course_list_selection=(app.courses_generator.data?app.courses_generator.data.length:0)-1:(app.course_list_selection++,app.course_list_selection%=app.courses_generator?app.courses_generator.data.length:0);app.fillSchedule();var b=document.getElementById("Range");b.max=app.courses_generator?app.courses_generator.data.length-1:0;b.value=app.course_list_selection;a.innerText=
app.courses_generator&&app.courses_generator.done?"Loop":"Next"}};
app.changedTerm=function(a,b){a=void 0===a?!1:a;b=void 0===b?null:b;a||null===b||!app.changed()||window.confirm("Are you sure you want to discard your changes?")?1==a||app.clear(!a&&null!==b&&app.changed(),"first"==a)?(b&&(b.firstChild&&""==b.firstChild.value&&b.removeChild(b.firstChild),app.term=b.value),app.term&&(app.course=null,document.getElementById("selectBox").value="",document.getElementById("searchBox").value="",app.selected=[],app.course_list_selection=0,b=document.getElementById("Range"),
b.max=0,b.value=0,app.courses_generator=null,app.savedCourseGenerator="","first"!=a&&app.fillSchedule(),app.percent="",document.getElementById("coursesBox").style.display="none",document.getElementById("loadingCourses").style.display="",app.termCacher.push(app.term,function(a){return function(b){app.courses=b;app.genDivs();app.fillSchedule();app.fillSearch();app.loadHash("first"==a);b=document.getElementById("notes");null!==b&&app.updateNotes(b)}}(a)))):document.getElementById("termSelect").value=
app.term:document.getElementById("termSelect").value=app.term};
app.genDivs=function(a){app.courses_manual="";for(a=0;a<app.courses.length;a++)app.courses_manual+='<option value="'+app.courses[a].index+'">'+app.courses[a].subject+" "+app.courses[a].courseNumber+(app.courses[a].sessionMod?app.courses[a].sessionMod:"")+": "+app.courses[a].title+"</option>";app.courses_auto="";for(a=0;a<app.courses.length;++a)if(0==a||app.courses[a].subject+app.courses[a].courseNumber!=app.courses[a-1].subject+app.courses[a-1].courseNumber)app.courses_auto+='<option value="'+app.courses[a].index+
'">'+app.courses[a].subject+" "+app.courses[a].courseNumber+": "+app.courses[a].title+"</option>";document.getElementById("coursesBox").style.display="";document.getElementById("loadingCourses").style.display="none"};app.updateTerms=function(){for(var a=document.getElementById("termSelect");a.lastChild;)a.removeChild(a.lastChild);for(var b=0;b<app.terms.length;b++){var c=app.terms[b],d=document.createElement("option");d.value=c.URLcode;d.innerText=c.title;a.appendChild(d)}a.value=app.term};
app.updatePercent=function(){document.getElementById("loadingCourses").innerText="Loading Courses... "+app.percent};app.updateNotes=function(a){a&&a.style.height!=a.scrollHeight+25+"px"&&(a.style.height="25px",a.style.height=a.scrollHeight+25+"px",app.saveMarker())};app.fillSearch=function(a){a=void 0===a?null:a;var b=document.getElementById("selectBox"),c=b.value;b.innerHTML=app.autoFilter(a);b.value=c;app.hideSearch()};
app.autoFilter=function(a){app.mode=a?a.value:app.mode;return"Manual"==app.mode?app.courses_manual:app.courses_auto};app.hideSearch=function(a){if(a=void 0===a?null:a)app.closed=a.checked,location.hash=app.generateHash(!1);a=document.getElementById("selectBox").children;for(var b=document.getElementById("searchBox").value.toLowerCase(),c=1;c<a.length;++c)a[c].style.display=app.filterSearch(app.courses[a[c].value],b)?"":"none"};
app.filterSearch=function(a,b){return null===a||-1!==app.selected.indexOf(a)||!app.closed&&("Manual"==app.mode?0>=a.seatsAvailable:a.home.alts.map(function(a){return a.map(function(a){return 0>=a.seatsAvailable}).reduce(function(a,b){return a&&b},!0)}).reduce(function(a,b){return a||b},!1))||b&&!(-1<(a.subject+" "+a.courseNumber).toLowerCase().indexOf(b)||-1<a.title.toLowerCase().indexOf(b)||a.URLcode.toString()==b)||"Automatic"==app.mode&&a.home.alts.reduce(function(a,b){return a.concat(b)},[]).some(function(a){return app.selected.includes(a)})?
!1:!0};var animator={element:void 0,down:function(a){return function(b){window.addEventListener("selectstart",animator.disableSelect);animator.element=a;animator.element.style.position="relative";animator.startX=b.clientX;animator.startY=b.clientY;animator.startCenterX=animator.element.offsetLeft+animator.element.offsetWidth/2;animator.startCenterY=animator.element.offsetTop+animator.element.offsetHeight/2}},move:function(a){if(void 0!==animator.element){animator.element.style.top=(a.clientY-animator.startY).toString()+
"px";animator.element.style.left=(a.clientX-animator.startX).toString()+"px";var b=animator.element.offsetLeft+animator.element.offsetWidth/2;animator.element.nextSibling&&b>animator.element.nextSibling.offsetLeft+animator.element.nextSibling.offsetWidth/2&&(animator.element.parentNode.insertBefore(animator.element.nextSibling,animator.element),animator.startX+=b-animator.startCenterX,animator.startCenterX=b,animator.element.style.left=(a.clientX-animator.startX).toString()+"px");animator.element.previousSibling&&
b<animator.element.previousSibling.offsetLeft+animator.element.previousSibling.offsetWidth/2&&(animator.element.parentNode.insertBefore(animator.element,animator.element.previousSibling),animator.startX+=b-animator.startCenterX,animator.startCenterX=b,animator.element.style.left=(a.clientX-animator.startX).toString()+"px")}},up:function(a){if(void 0!==animator.element){window.removeEventListener("selectstart",animator.disableSelect);animator.element.style.top="auto";animator.element.style.left="auto";
animator.element.style.position="static";if(5<Math.abs(a.clientX-animator.startX)||5<Math.abs(a.clientY-animator.startY)){var b=document.getElementById("saves").children,c=[];for(a=0;a<b.length;++a)c.push([b[a].innerText,JSON.parse(window.localStorage.schedules)[b[a].innerText]]);b={};for(a=0;a<c.length;++a)b[c[a][0]]=c[a][1];window.localStorage.schedules=JSON.stringify(b)}else{c=animator.element.parentElement;for(a=0;a<c.children.length;++a)c.children[a].classList.remove("preselect");animator.element.classList.add("preselect");
b=app.load(animator.element.innerText);for(a=0;a<c.children.length;++a)c.children[a].classList.remove("preselect");if(b){for(a=0;a<c.children.length;++a)c.children[a].classList.remove("selected");animator.element.classList.add("selected");app.saveMarker()}}animator.element=void 0}},disableSelect:function(a){a.preventDefault()}};window.onmouseup=animator.up;window.onmousemove=animator.move;
app.saveMarker=function(){document.getElementById("marker-save").style.display=app.changed()&&app.selected.length?"":"none";document.getElementById("marker-discard").style.display=app.changed()&&app.currentstorage&&app.selected.length?"":"none";document.getElementById("marker-saveAsNew").style.display=app.currentstorage?"":"none";document.getElementById("marker-delete").style.display=app.currentstorage?"":"none";document.getElementById("marker-export").style.display=app.selected.length?"":"none";
document.getElementById("marker-new").style.display=app.currentstorage||app.selected.length?"":"none"};
app.updateSaved=function(){var a=Object.keys(JSON.parse(window.localStorage.schedules));if(a.length){for(var b=document.getElementById("saves"),c=0;c<b.children.length;++c){var d=b.children[c],e=a.findIndex(function(a){return a==d.innerText});-1==e?(b.removeChild(d),--c):a.splice(e,1)}for(c=0;c<a.length;++c)e=document.createElement("div"),e.className="option draggable",e.innerText=a[c],b.appendChild(e);a=b.children;for(c=0;c<a.length;++c)a[c].onmousedown=animator.down(a[c]);for(c=0;c<a.length;++c)b=
a[c],app.currentstorage==b.innerText?b.classList.add("selected"):b.classList.remove("selected");app.saveMarker()}};
app.save=function(){if(!app.currentstorage){var a=window.prompt("Please enter a name for the schedule");if(!a)return;app.currentstorage=a}window.localStorage.schedules||window.localStorage.setItem("schedules","{}");a=JSON.parse(window.localStorage.schedules);a[app.currentstorage]=app.generateHash(!0);window.localStorage.setItem("schedules",JSON.stringify(a));window.localStorage.setItem("lastSaved",app.generateHash(!1)+"?"+app.currentstorage);app.selected=[];app.course_list_selection=0;a=document.getElementById("Range");
a.max=0;a.value=0;app.courses_generator=null;app.savedCourseGenerator="";app.loadHash();app.autoBar();app.updateSaved()};
app.load=function(a){if(null===a||app.changed()&&!window.confirm("Are you sure you want to discard your changes?"))return!1;ga("send","event","schedule","load");app.currentstorage=a;document.getElementById("notes").value=JSON.parse(window.localStorage.schedules)[a].split("+")[1];app.disableOnHashChange=!0;location.hash=JSON.parse(window.localStorage.schedules)[a].split("+")[0];a=app.getHash().split("=")[0].substr(1);a=app.terms.map(function(a){return a.URLcode}).indexOf(a);-1<a&&(app.term!=app.terms[a].URLcode?
app.term=app.terms[a].URLcode:(app.course=null,document.getElementById("selectBox").value=""),app.updateTerms(),app.changedTerm(!0));app.updateNotes(document.getElementById("notes"));app.fillSchedule();window.localStorage.setItem("lastSaved",app.generateHash(!1)+"?"+app.currentstorage);return!0};app.discard=function(){var a=app.currentstorage;app.currentstorage=null;app.changed()&&!app.load(a)?app.currentstorage=a:(ga("send","event","schedule","discard"),window.localStorage.setItem("lastSaved","{}"))};
app.saveNew=function(){ga("send","event","schedule","save-new");app.currentstorage=null;app.save()};app.deleteSchedule=function(){if(window.confirm("Are you sure you want to delete the schedule "+app.currentstorage+"?")){var a=JSON.parse(window.localStorage.schedules);delete a[app.currentstorage];window.localStorage.setItem("schedules",JSON.stringify(a));app.clear(!0);app.updateSaved();app.fillSchedule();window.localStorage.setItem("lastSaved","{}")}};
app.clear=function(a,b){b=void 0===b?!1:b;if((void 0===a||!a)&&app.changed()&&!window.confirm("Are you sure you want to discard your changes?"))return location.hash=app.generateHash(!1),!1;ga("send","event","schedule","new");document.getElementById("selectBox").value="";app.course_list_selection=0;a=document.getElementById("Range");a.max=0;a.value=0;app.courses_generator=null;app.savedCourseGenerator="";b||(location.hash="");document.getElementById("notes").value="";app.course=null;app.selected=[];
app.currentstorage=null;app.updateSaved();app.fillSchedule();app.hideSearch();window.localStorage.setItem("lastSaved","{}");return!0};app.showExport=function(){document.getElementById("export").style.display="";document.getElementById("export-link").value=location.href;document.getElementById("export-text").value=app.selected.map(function(a){return a.courseRegistrationCode+": "+a.subject+" "+a.courseNumber}).join("\n")};var Lazy=function(a){this.core=a;this.data=[];this.filters=[];this.done=!1};
Lazy.prototype.get=function(a,b){b=void 0===b?!1:b;if(Array.isArray(this.core))return this.core;for(;!this.done&&this.data.length<=a;){var c=this.core.next();if(c.done){this.done=!0;break}this.filters.reduce(function(a,b){return a&&b(c.value)},!0)&&this.data.push({value:c.value,selected:c.value.filter(function(a){return!a.home.alts.reduce(function(a,b){return a.concat(b)},[]).includes(null!==app.course?app.courses[app.course]:null)})})}a=this.data[a];if(!a)return!1;b&&(app.selected=a.selected);location.hash=
app.generateHash(!1);return a.value};Lazy.prototype.filter=function(a){this.filters.push(a);return this};
app.autoConstruct=function(a,b){b=void 0===b?!1:b;if(void 0===a[0]||null===a[0])return new Lazy([]);void 0!==a.slice(-1)[0]&&null!==a.slice(-1)[0]||a.pop();if("Manual"==app.mode){a=app.closed||b?a:a.filter(function(a){return 0<a.seatsAvailable||a.locked});if("M"+a.map(function(a){return a.URLcode}).join()==app.savedCourseGenerator)return app.courses_generator||new Lazy([]);"A"==app.savedCourseGenerator[0]&&null!=app.course&&(app.courses_generator&&app.courses_generator.get(app.course_list_selection)&&
(b=app.courses_generator.get(app.course_list_selection),a=Array.isArray(b)?b:[]),app.course=a.filter(function(a){return null!==app.course&&a.home==app.courses[app.course].home})[0].index,document.getElementById("selectBox").value=app.course.toString());app.savedCourseGenerator="M"+a.map(function(a){return a.URLcode}).join();app.courses_generator=new Lazy(a);return app.courses_generator}if("A"+app.removeDuplicatesBy(function(a){return a.home},a).map(function(a){return a.home.URLcode}).filter(function(a){return a}).join()+
(app.closed?"C":"")==app.savedCourseGenerator)return app.courses_generator||new Lazy([]);"M"==app.savedCourseGenerator[0]&&app.course&&(app.course=app.courses[app.course].home.index,document.getElementById("selectBox").value=app.course.toString());app.course_list_selection=0;b=document.getElementById("Range");b.max=0;b.value=0;app.courses_generator=(new Lazy(app.cartesianProduct(app.removeDuplicatesBy(function(a){return a.home},a).reduce(function(b,d){d.home.alts.forEach(function(c){var d=c.filter(function(a){return a.locked});
d.length?c=d:a.forEach(function(a){c.includes(a)&&(c=c.filter(function(b){return b!=a}),c.unshift(a))});b.push(app.closed?c:c.filter(function(a){return 0<a.seatsAvailable||a.locked}))});return b},[])))).filter(app.schedCompat);app.savedCourseGenerator="A"+app.removeDuplicatesBy(function(a){return a.home},a).map(function(a){return a.home.URLcode}).filter(function(a){return a}).join()+(app.closed?"C":"");return app.courses_generator};
app.removeDuplicatesBy=function(a,b){var c=new Set;return b.filter(function(b){b=a(b);var d=!c.has(b);d&&c.add(b);return d})};
app.cartesianProduct=function $jscomp$generator$function(a){var c,d,e;return $jscomp.generator.createGenerator($jscomp$generator$function,function(f){switch(f.nextAddress){case 1:if(a.map(function(a){return 0==a.length}).reduce(function(a,c){return a||c},!1))return f.return();if(!(1>=a.length)){f.jumpTo(2);break}c=0;case 3:if(!(c<a[0].length)){f.jumpTo(5);break}return f.yield([a[0][c]],4);case 4:++c;f.jumpTo(3);break;case 5:return f.return();case 2:d=Array(a.length).fill(0,0,a.length);case 7:for(c=
0;c<d.length-1;++c)d[c]>a[c].length-1&&(d[c]=0,d[c+1]++);if(d[d.length-1]>a[a.length-1].length-1)return f.return();e=Array(a.length-1);for(c=0;c<a.length;++c)e[c]=a[c][d[c]];return f.yield(e,9);case 9:d[0]++,f.jumpTo(7)}})};app.schedCompat=function(a){if(1==a.length)return!0;for(var b=[a[0]],c=1;c<a.length;){for(var d=0;d<b.length;++d)if(!app.courseCompat(b[d],a[c]))return!1;b.push(a[c++])}return!0};
app.courseCompat=function(a,b){return a.meetings.reduce(function(a,d){return a&&b.meetings.reduce(function(a,b){return a&&app.meetingCompat(d,b)},!0)},!0)};app.meetingCompat=function(a,b){return"monday tuesday wednesday thursday friday saturday sunday".split(" ").reduce(function(c,d){return c||a[d]&&b[d]},!1)?!(a.beginTime>=b.beginTime&&a.beginTime<b.endTime||a.endTime>b.beginTime&&a.endTime<=b.endTime||b.endTime>a.beginTime&&b.endTime<=a.endTime||b.endTime>a.beginTime&&b.endTime<=a.endTime):!0};window.onload=function(){void 0==window.localStorage.lastSaved&&(window.localStorage.lastSaved="");void 0==window.localStorage.schedules&&(window.localStorage.schedules="{}");void 0==window.localStorage.darkMode&&(window.localStorage.darkMode="false");void 0==window.localStorage.darkMode&&(window.localStorage.darkMode="false");var a=document.getElementById("styleSlider");a.checked="true"==window.localStorage.darkMode;change_style(a);app.mode=document.getElementById("Manual").checked?"Manual":"Automatic";
app.closed=!!app.getHash().split("&")[1];document.getElementById("closedCheck").checked=app.closed;app_config.CORStest?(new Searcher("test")).start(function(a){a?(document.getElementById("loading").style.display="none",document.getElementById("main").style.display=""):(document.getElementById("loading").style.display="none",document.getElementById("cors").style.display="")}):(document.getElementById("loading").style.display="none",document.getElementById("main").style.display="");(new Searcher("terms")).start(function(a){app.terms=
app_config.PROCESSgetTerms(a);a=(app.getHash().split("=")[1]||"").split("&")[0].length?app.terms.map(function(a){return a.URLcode}).indexOf(app.getHash().split("=")[0].substr(1)):-1;(app.getHash().split("=")[1]||"").split("&")[0].length&&-1<a?(app.term=app.terms[a].URLcode,app.updateTerms(),app.changedTerm("first")):(app.term=app.terms[0].URLcode,app.updateTerms(),app.changedTerm(!1));document.getElementById("termSelect").value=app.term;app.updateSaved()});var b=document.getElementById("nextButton"),
c={waiter:null,advanceNextButton:function(a){app.genNext(b);c.waiter=setTimeout(c.advanceNextButton,1)},pressingDown:function(a){app.genNext(b);c.waiter=setTimeout(c.advanceNextButton,750)},notPressingDown:function(a){clearTimeout(c.waiter);c.waiter=null}};b.addEventListener("mousedown",c.pressingDown,!1);b.addEventListener("mouseup",c.notPressingDown,!1);b.addEventListener("mouseleave",c.notPressingDown,!1);b.addEventListener("touchstart",c.pressingDown,!1);b.addEventListener("touchend",c.notPressingDown,
!1);(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="//www.heeduser.com/supfiles/Script/widget.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();document.getElementById("feedback").innerHTML='<a id="heeduser_wb" href="JavaScript:heeduser_openwidget(heeduser_url,\''+_heeduser.widget_layout+"')\">Leave your feedback!</a>"};
var _heeduser={type:"button",community:"sitscheduler",url:"http://sitscheduler.heeduser.com",placement:"middle-right",color:"#202021",widget_layout:"full",sso_token:""},heeduser_url=_heeduser.url+"/FeedbackWidget/Widget.aspx?sso_token="+encodeURIComponent(_heeduser.sso_token);
