var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var h=e[g];if(!(h in d))return;d=d[h]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,g){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.polyfill("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,c||0)}},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var g=a[e];if(b.call(c,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).i}},"es6","es3");$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
$jscomp.polyfill("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,d,e){return c==a&&"q"==d&&e==b}}));return!0===b.q}catch(c){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),l=new a([[k,2],[m,3]]);if(2!=l.get(k)||3!=l.get(m))return!1;l.delete(k);l.set(m,4);return!l.has(k)&&4==l.get(m)}catch(p){return!1}}function c(){}function d(k){var m=typeof k;return"object"===m&&null!==k||"function"===m}function e(k){if(!$jscomp.owns(k,h)){var m=new c;$jscomp.defineProperty(k,h,{value:m})}}function g(k){if(!$jscomp.ISOLATE_POLYFILLS){var m=Object[k];m&&(Object[k]=
function(l){if(l instanceof c)return l;Object.isExtensible(l)&&e(l);return m(l)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var h="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var n=0,f=function(k){this.id_=(n+=Math.random()+1).toString();if(k){k=$jscomp.makeIterator(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}};f.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");
e(k);if(!$jscomp.owns(k,h))throw Error("WeakMap key fail: "+k);k[h][this.id_]=m;return this};f.prototype.get=function(k){return d(k)&&$jscomp.owns(k,h)?k[h][this.id_]:void 0};f.prototype.has=function(k){return d(k)&&$jscomp.owns(k,h)&&$jscomp.owns(k[h],this.id_)};f.prototype.delete=function(k){return d(k)&&$jscomp.owns(k,h)&&$jscomp.owns(k[h],this.id_)?delete k[h][this.id_]:!1};return f},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),k=new a($jscomp.makeIterator([[f,"s"]]));if("s"!=k.get(f)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var m=k.entries(),l=m.next();if(l.done||l.value[0]!=f||"s"!=l.value[1])return!1;l=m.next();return l.done||4!=l.value[0].x||"t"!=l.value[1]||!m.next().done?!1:!0}catch(p){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=new WeakMap,d=function(f){this.data_={};this.head_=h();this.size=0;if(f){f=$jscomp.makeIterator(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}};d.prototype.set=function(f,k){f=0===f?0:f;var m=e(this,f);m.list||(m.list=this.data_[m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:f,value:k},m.list.push(m.entry),
this.head_.previous.next=m.entry,this.head_.previous=m.entry,this.size++);return this};d.prototype.delete=function(f){f=e(this,f);return f.entry&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.data_[f.id],f.entry.previous.next=f.entry.next,f.entry.next.previous=f.entry.previous,f.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=h();this.size=0};d.prototype.has=function(f){return!!e(this,f).entry};d.prototype.get=function(f){return(f=
e(this,f).entry)&&f.value};d.prototype.entries=function(){return g(this,function(f){return[f.key,f.value]})};d.prototype.keys=function(){return g(this,function(f){return f.key})};d.prototype.values=function(){return g(this,function(f){return f.value})};d.prototype.forEach=function(f,k){for(var m=this.entries(),l;!(l=m.next()).done;)l=l.value,f.call(k,l[1],l[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(f,k){var m=k&&typeof k;"object"==m||"function"==m?c.has(k)?m=c.get(k):
(m=""+ ++n,c.set(k,m)):m="p_"+k;var l=f.data_[m];if(l&&$jscomp.owns(f.data_,m))for(f=0;f<l.length;f++){var p=l[f];if(k!==k&&p.key!==p.key||k===p.key)return{id:m,list:l,index:f,entry:p}}return{id:m,list:l,index:-1,entry:void 0}},g=function(f,k){var m=f.head_;return $jscomp.iteratorPrototype(function(){if(m){for(;m.head!=f.head_;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})},h=function(){var f={};return f.previous=f.next=f.head=f},n=0;
return d},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),e=new a($jscomp.makeIterator([d]));if(!e.has(d)||1!=e.size||e.add(d)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var g=e.entries(),h=g.next();if(h.done||h.value[0]!=d||h.value[1]!=d)return!1;h=g.next();return h.done||h.value[0]==d||4!=h.value[0].x||h.value[1]!=h.value[0]?!1:g.next().done}catch(n){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var c=function(d){this.map_=new Map;if(d){d=$jscomp.makeIterator(d);for(var e;!(e=d.next()).done;)this.add(e.value)}this.size=this.map_.size};c.prototype.add=function(d){d=0===d?0:d;this.map_.set(d,d);this.size=this.map_.size;return this};c.prototype.delete=function(d){d=this.map_.delete(d);this.size=this.map_.size;return d};c.prototype.clear=function(){this.map_.clear();this.size=0};c.prototype.has=
function(d){return this.map_.has(d)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(d,e){var g=this;this.map_.forEach(function(h){return d.call(e,h,h,g)})};return c},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}},"es6","es3");$jscomp.typedArrayFill=function(a){return a?a:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");function ga(a,b,c,d){}(function(a,b,c,d,e){a.GoogleAnalyticsObject=e;a[e]=a[e]||function(){(a[e].q=a[e].q||[]).push(arguments)};a[e].l=1*new Date;var g=b.createElement(c);b=b.getElementsByTagName(c)[0];g.async=1;g.src=d;b.parentNode.insertBefore(g,b)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create","UA-96461430-1","auto");ga("send","pageview");var app_config={test_percent_cap:100,chunk:300,useCredentials:!1,URLprefix:"https://stevens-scheduler.cfapps.io/p/"},GETPOST;app_config.URLgetTerms=function(a){a.openMethod="GET";a.url=app_config.URLprefix+"terms"};app_config.URLgetCourses=function(a,b,c,d){a.openMethod="GET";a.url=app_config.URLprefix+b};app_config.URLgetDescription=function(a,b,c){a.openMethod="GET";a.url=app_config.URLprefix+"desc/"+c};app_config.URLgetCourseTotalCount=function(a,b){a.url=""};
app_config.URLtest=function(a){a.openMethod="GET";a.url="https://stevens-scheduler.cfapps.io/"};app_config.URLprime=function(a,b){a.openMethod="GET";a.url=""};var Term;
app_config.PROCESSgetTerms=function(a){var b=[];JSON.parse(a).forEach(function(c){var d=c.substr(0,4),e=c.substr(4);d+=" ";switch(e){case "S":d+="Spring";break;case "F":d+="Fall";break;case "A":d+="Summer I";break;case "B":d+="Summer II";break;case "W":d+="Winter";break;default:d+="undefined"}b.push({URLcode:c,title:d+(" ("+c+")")})});return b};app_config.PROCESSgetCourseTotalCount=function(a){return 1};var Meeting,Course;
Date.prototype.stdTimezoneOffset=function(){var a=new Date(this.getFullYear(),0,1),b=new Date(this.getFullYear(),6,1);return Math.max(a.getTimezoneOffset(),b.getTimezoneOffset())};Date.prototype.isDstObserved=function(){return this.getTimezoneOffset()<this.stdTimezoneOffset()};
app_config.PROCESSgetCourses=function(a){a=JSON.parse(a);var b=[],c=new Date;a.forEach(function(d){var e={};try{e.courseNumber=d.section.match(/\d+/g)[0];e.subject=d.section.match(/[a-zA-Z]+/g)[0];e.sessionMod=d.section.match(/[a-zA-Z]+/g)[1];e.courseRegistrationCode=d.callNumber;e.title=d.title;e.URLcode=e.courseRegistrationCode;e.GETcode=e.subject+" "+e.courseNumber+e.sessionMod;e.credits=d.credits;e.faculty=d.instructor;var g=d.section.match(/[a-zA-Z]+/g)[1];e.scheduleTypeDescription=1>=g.length?
"Lecture":g[0];e.maximumEnrollment=parseInt(d.maxEnrollment,10);e.seatsAvailable=d.seatsAvailable?parseInt(d.seatsAvailable,10):e.maximumEnrollment-parseInt(d.currentEnrollment,10);e.meetings=d.daysTimeLocation.filter(function(h){return void 0!=h.startTime&&void 0!=h.endTime}).map(function(h){if("WS"==h.site||"WEB"==h.room)return e.scheduleTypeDescription="L",{building:"ONLINE",room:"ONLINE",monday:!1,tuesday:!1,wednesday:!1,thursday:!1,friday:!1,saturday:!1,sunday:!1};if("TBA"!=h.day){var n={building:h.building,
room:h.room,monday:h.day.includes("M"),tuesday:h.day.includes("T"),wednesday:h.day.includes("W"),thursday:h.day.includes("R"),friday:h.day.includes("F"),saturday:!1,sunday:!1};n.beginTime=h.startTime.substr(0,h.startTime.length-4).split(":");n.beginTime=n.beginTime.join("");n.endTime=h.endTime.substr(0,h.endTime.length-4).split(":");n.endTime=n.endTime.join("");n.beginTime=(parseInt(n.beginTime,10)+400+100*!c.isDstObserved()).toString();n.endTime=(parseInt(n.endTime,10)+400+100*!c.isDstObserved()).toString();
return n}}).filter(function(h){return void 0!==h});"W"==e.scheduleTypeDescription&&e.meetings.push({building:"ONLINE"});b.push(e)}catch(h){console.error("Something's wrong with a course. Ignoring: ",e)}});return b.map(function(d){"S"==d.scheduleTypeDescription&&(d.scheduleTypeDescription=d.sessionMod.substr(1)[0]||"");return d})};
app_config.PROCESSgetDescription=function(a){for(a=a.replace(/<br>/g,"\r\n").replace(/<BR>/g,"\r\n").trim();"\r\n"==a.substr(0,2);)a=a.substr(2,a.length);for(;"\r\n"==a.substr(a.length-2,a.length-1);)a=a.substr(0,a.length-2);return a};app_config.collegeName="Stevens Institute of Technology";app_config.collegeNameShort="SIT";app_config.siteTitle="SIT Scheduler - Course Scheduler for Stevens Institute of Technology";app_config.siteTitleShort="SIT Scheduler";app_config.courseRegistrationCodeName="CN";
app_config.getLogoName=function(a){return"Stevens-Official-"+(a?"WhiteKO":"PMSColor")+"-R.svg"};app_config.CORStest=!1;app_config.CORScustom="";document.title=app_config.siteTitle;
!0===app_config.CORStest?document.getElementById("cors").innerHTML="Hi, and welcome to "+app_config.siteTitleShort+"! This is a tool for creating, editing, testing, and sharing schedules for "+app_config.collegeName+".<br><br>I can see you're locked out of the "+app_config.collegeNameShort+" systems. Unfortunately, there isn't anything the developer can do about this problem. This is because "+app_config.collegeNameShort+" won't recognize this website as friendly.<br><b>In order to use this tool, please download and use a CORS-everywhere extension</b> and refresh. This intercepts data coming from "+app_config.collegeNameShort+
"'s servers and makes your browser think "+app_config.collegeNameShort+' trusts us, so that your browser doesn\'t lock you out. Here are a few I recommend:<br><a href="https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/">Firefox</a><br>For Chrome, it\'s a bit more envolved. See <a href="https://www.codevoila.com/post/75/how-to-disable-same-origin-policy-in-chrome">this</a> for more details.<br>NOTE: it is technically unsafe to browse with CORS-everywhere enabled. Please, disable it when not using this tool.<br><br><b>'+
app_config.CORScustom+"</b>":document.getElementById("cors").innerHTML="Hi, and welcome to "+app_config.siteTitleShort+"! This is a tool for creating, editing, testing, and sharing schedules for "+app_config.collegeName+".<br><br><b>The "+app_config.collegeNameShort+" servers seem to be down right now. Check back later.</b><br><br>If you're a developer, this might be a CORS related issue.";
(function(){for(var a=document.getElementById("schedThead"),b="Monday Tuesday Wednesday Thursday Friday Saturday Sunday".split(" "),c=0;c<b.length;++c){var d=b[c],e=document.createElement("th");e.innerText=d;a.appendChild(e)}})();
(function(){var a=document.getElementById("schedTbody"),b=[8,9,10,11,12,13,14,15,16,17,18,19,20],c="monday tuesday wednesday thursday friday saturday sunday".split(" "),d=document.createElement("tr"),e=document.createElement("td");e.className="time";d.appendChild(e);e=document.createElement("td");e.className="block";var g=document.createElement("div");g.className="wrapper";var h=document.createElement("div");h.className="wrapperInternal";g.appendChild(h);g.appendChild(document.createElement("div"));
g.appendChild(document.createElement("div"));e.appendChild(g);for(g=0;g<b.length;++g){h=b[g];var n=d.cloneNode(!0);n.firstChild.innerText=(h-1)%12+1+":00";for(var f=0;f<c.length;++f){var k=c[f],m=e.cloneNode(!0);m.firstChild.firstChild.setAttribute("data-hour",h);m.firstChild.firstChild.setAttribute("data-day",k);n.appendChild(m)}a.appendChild(n)}})();
(function(){var a=document.getElementById("schedThead").children;a[6].style.display="none";a[7].style.display="none";a=document.getElementById("schedTbody").children;for(var b=0;b<a.length;++b)a[b].children[6].style.display="none",a[b].children[7].style.display="none"})();window.onresize=function(){var a=document.getElementById("weekTableWrapper");document.getElementById("weekTableHead").style.borderRight=(a.offsetWidth-a.clientWidth).toString()+"px solid "+getComputedStyle(document.getElementById("schedThead")).backgroundColor};var postProcessCourses=function(a){return a.filter(function(b){return b.meetings.reduce(function(c,d){return c||"monday tuesday wednesday thursday friday saturday sunday".split(" ").reduce(function(e,g){return e||d[g]},!1)||"ONLINE"==d.building},!1)}).map(function(b){b.scheduleTypeDescription.includes("Honors ")&&(b.scheduleTypeDescription=b.scheduleTypeDescription.split("Honors ")[1]);return b}).reduce(function(b,c){return 0<b.length?(b[b.length-1][0].subject+b[b.length-1][0].courseNumber==c.subject+
c.courseNumber?b[b.length-1].push(c):b.push([c]),b):[[c]]},[]).map(function(b){b[0].home=b[0];b[0].alts=[[b[0]]];for(var c=1;c<b.length;++c){b[c].home=b[0];var d=b[0].alts.findIndex(function(e){return e[0].scheduleTypeDescription==b[c].scheduleTypeDescription});-1<d?b[0].alts[d].push(b[c]):b[0].alts.push([b[c]])}return b}).reduce(function(b,c){return b.concat(c)},[]).map(function(b,c){b.index=c;return b})},Searcher=function(a,b,c,d){this.term=void 0===b?"":b;this.data=[];this.done=!1;this.offset=
void 0===c?"":c;this.size=void 0===d?0:d;this.xhr=null;this.type=a};
Searcher.prototype.start=function(a,b){a=void 0===a?null:a;b=void 0===b?null:b;if(!this.xhr&&!this.done){var c={postData:"0",openMethod:"",url:""};switch(this.type){case "prime":app_config.URLprime(c,this.term);break;case "count":app_config.URLgetCourseTotalCount(c,this.term);break;case "courses":app_config.URLgetCourses(c,this.term,this.offset.toString(),this.size);break;case "terms":app_config.URLgetTerms(c);break;case "desc":app_config.URLgetDescription(c,this.term,this.offset.toString());break;
case "test":app_config.URLtest(c);break;default:console.error("Invalid type in Searcher")}if(""==c.url){if("prime"==this.type||"count"==this.type){this.xhr=null;this.done=!0;a(!1);return}console.error("url not set for request of type "+this.type+". There's an erorr in config.js")}""==c.openMethod&&console.error("openMethod not set for request of type "+this.type+". There's an erorr in config.js");"POST"==c.openMethod&&"0"==c.postData&&console.error("postData is missing for POST request of type "+
this.type+". There's an erorr in config.js");this.xhr=new XMLHttpRequest;this.xhr.onreadystatechange=function(d){return function(){4==this.readyState&&(this.done=!0,d.xhr=null);"test"==d.type&&4===this.readyState&&0===this.status?(!0===app_config.CORStest?console.error("CORS DENIED - please enable a CORS-everywhere extension or ask "+app_config.collegeNameShort+" to let us in"):console.error("Can't communicate with "+app_config.collegeName+" servers. They're probable down right now - check back later."),
a&&a(!1)):"test"==d.type&&4===this.readyState?a&&a(!0):"test"!=d.type&&(4===this.readyState&&200===this.status?(a&&a(this.responseText),d.done=!0,d.xhr=null):200!=this.status&&4==this.readyState&&(b?b(this.status,this.responseText):console.error("Unhandled erorr on HTTP request: ",this.status.toString())))}}(this);this.xhr.open(c.openMethod,c.url);this.xhr.withCredentials=app_config.useCredentials;"POST"==c.openMethod&&this.xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
this.xhr.send(c.postData)}};Searcher.prototype.stop=function(){this.xhr&&!this.done&&(this.xhr.abort(),this.xhr=null)};var TermManager=function(a){this.term=a;this.data=[];this.done=!1;this.requests=[];this.headRequest=null;this.main_callback_wrapper={callback:null};this.totalCount=0};
TermManager.prototype.start=function(a,b){b=void 0===b?!1:b;this.main_callback_wrapper.callback=a;this.done?a&&a(this.data):this.headRequest||(a=function(c){return function(d){c.requests.length?(d=c.data.reduce(function(e,g){return e+g.courses.length},0),0!==c.totalCount&&(app.percent=d.toString()+"/"+c.totalCount.toString(),app.updatePercent()),c.headRequest=null,c.requests.forEach(function(e){e.start(function(g){g=app_config.PROCESSgetCourses(g);c.data.push({courses:g,offset:e.offset});g=c.data.reduce(function(f,
k){return f+k.courses.length},0);0!==c.totalCount&&(app.percent=g.toString()+"/"+c.totalCount.toString(),app.updatePercent());if(0===c.totalCount||g>=app_config.test_percent_cap*c.totalCount/100){app.percent+="\nProcessng courses...";app.updatePercent();c.data=postProcessCourses(c.data.sort(function(f,k){return f.offset-k.offset}).reduce(function(f,k){return f.concat(k.courses)},[]));c.done=!0;c.requests=[];c.main_callback_wrapper.callback&&c.main_callback_wrapper.callback(c.data);g=document.getElementById("saves").children;
for(var h=[],n=0;n<g.length;++n)h.push(JSON.parse(window.localStorage.schedules)[g[n].innerText].split("=")[0]);g=app.termCacher.termManagers.filter(function(f){return f.done}).map(function(f){return f.term});for(n=0;n<h.length;++n)if(!g.find(function(f){return f==h[n]})){app.termCacher.push(h[n],null);break}}},function(g,h){404==g&&("Cache not warm"==h?alert("It looks like the server just started recently and has not downloaded data for this term yet. Please try again in a few minutes."):""!==h&&
console.error("Unhandled error "+g+":"+h))})})):(app.percent="0/?",app.updatePercent(),c.headRequest=new Searcher("count",c.term),c.headRequest.start(function(e){c.headRequest=null;if(!1===e)app.percent="",app.updatePercent(),e=new Searcher("courses",c.term,"0",0),e.offset=0,c.requests.push(e);else{c.totalCount=app_config.PROCESSgetCourseTotalCount(e);app.percent="0/"+c.totalCount.toString();app.updatePercent();e=[];for(var g=0;g<app_config.test_percent_cap*c.totalCount/100;g+=app_config.chunk)e.push(g);
e.forEach(function(h){var n=new Searcher("courses",c.term,h,app_config.chunk);n.offset=h;c.requests.push(n)})}c.start(c.main_callback_wrapper.callback,!0)}))}}(this),b?a(null):(this.headRequest=new Searcher("prime",this.term),this.headRequest.start(a)))};TermManager.prototype.stop=function(){this.done||(this.main_callback_wrapper.callback=null,this.headRequest&&(this.headRequest.stop(),this.headRequest=null),this.requests.forEach(function(a){a.stop()}))};
var TermCacher=function(){this.termManagers=[]};
TermCacher.prototype.push=function(a,b){b=void 0===b?null:b;var c=this.termManagers.findIndex(function(e){return e.term==a});if(-1<c&&this.termManagers[c].done)this.termManagers.forEach(function(e){e.main_callback_wrapper.callback=null}),this.termManagers[c].start(b);else{var d=null;-1<c&&(d=this.termManagers.splice(c,1)[0]);this.termManagers.forEach(function(e){e.stop()});this.termManagers.push(-1<c?d:new TermManager(a));this.termManagers[this.termManagers.length-1].start(b)}};var app={course:null,courses:[],selected:[],mode:"Manual",courses_generator:null,savedCourseGenerator:"0",course_list_selection:0,hovering:[],currentstorage:null,terms:[],term:"",courses_auto:"",courses_manual:"",closed:!1,percent:""};app.termCacher=new TermCacher;app.generateHash=function(a){var b=app.term+"=",c=app.selected;"Automatic"===app.mode&&app.courses_generator&&app.courses_generator.data&&app.courses_generator.data[app.course_list_selection]&&(c=app.courses_generator.data[app.course_list_selection].selected);b+=c.sort(function(d,e){return d.URLcode-e.URLcode}).map(function(d){return d.URLcode+(d.locked?"!":"")}).join();app.closed&&(b+="&C");!0===a&&(b+="+"+document.getElementById("notes").value);return b};app.getHash=function(){return decodeURIComponent(location.hash)};
app.changed=function(){if(0==app.selected.length)return!1;for(var a=document.getElementById("saves").children,b=!0,c=-1,d=0;d<a.length;++d)a[d].classList.contains("selected")&&(c=d);if(-1<c)b=JSON.parse(window.localStorage.schedules)[a[c].innerText]!=app.generateHash(!0);else for(d=0;d<a.length;++d)a[d].classList.contains("preselect")&&(b=JSON.parse(window.localStorage.schedules)[a[d].innerText]!=app.generateHash(!0));return b};
app.autoInAlts=function(a,b){return null==a||null==b?!1:"Manual"==app.mode?a==b:a.home==b.home};window.addEventListener("keydown",function(a){"Escape"==a.key&&(document.getElementById("selectBox").value="",app.course=null,app.savedCourseGenerator="",app.courses_generator=null,app.fillSchedule())});
var change_style=function(a){for(var b=!1,c=0;c<document.styleSheets.length;++c)null==document.styleSheets[c].href?b=!0:document.styleSheets[c].href.includes("style_dark.min.css")&&(document.styleSheets[c].disabled=!a.checked);if(b){window.localStorage.darkMode=!0;for(c=0;c<document.styleSheets.length;++c)document.styleSheets[c].href&&document.styleSheets[c].href.includes("style_dark.min.css")&&(document.styleSheets[c].disabled=!1);document.getElementById("logo").src=app_config.getLogoName(!0);a.style.display=
"none"}else document.getElementById("logo").src=app_config.getLogoName(a.checked),window.localStorage.darkMode=a.checked.toString()};app.autoAndLabs=function(a){return null==a?[]:"Manual"==app.mode?[a]:app.courses_generator?app.courses_generator.get(app.course_list_selection).filter(function(b){return b&&b.home==a.home}):[]};
app.fillSchedule=function(a){if(a=void 0===a?null:a)app.course_list_selection=a.value;app.course=""!=document.getElementById("selectBox").value?parseInt(document.getElementById("selectBox").value,10):null;var b=document.getElementsByClassName("wrapperInternal"),c=app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null),!0).get("Manual"==app.mode?0:app.course_list_selection);a=[];for(var d=0;d<b.length;++d){for(var e=b[d],g=e.getAttribute("data-day"),h=e.getAttribute("data-hour");e.firstChild;)e.removeChild(e.firstChild);
for(var n=0;n<c.length;++n){var f=c[n],k=app.courseHere(g,h,f);if(f&&k){var m=document.createElement("div");if("Automatic"==app.mode||!app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)){var l=document.createElement("div");l.className="autoLock";l.innerText=f.locked?"\ud83d\udd12":"\ud83d\udd13 ";l.onclick=function(q,u){return function(r){app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection,!0);q.locked=!q.locked;app.savedCourseGenerator=
"";app.fillSchedule();null===app.course||app.autoInAlts(app.courses[app.course],q)||(location.hash=app.generateHash(!1))}}(f,l);l.style.top=100*k.top+"%";m.appendChild(l)}l=document.createElement("div");l.className="item";var p=f.subject+" "+f.courseNumber+"\n"+f.title.replace(/&ndash;/g,"\u2013")+"\n"+(f.faculty.trim().length?f.faculty+"\n":"")+(k.loc.length?k.loc+"\n":"")+f.credits+" credit"+(1!=f.credits?"s":"")+"\n";void 0!==f.seatsAvailable&&void 0!==f.maximumEnrollment&&(p+=Math.max(0,f.seatsAvailable)+
"/"+f.maximumEnrollment+" seats open\n");void 0!==f.waitAvailable&&void 0!==f.waitAvailable&&(p+=f.waitAvailable+"/"+f.waitCapacity+" waitlist open\n");p+=app_config.courseRegistrationCodeName+": "+f.courseRegistrationCode+"\n";l.innerText=p;p=document.createElement("a");p.className="link";p.onclick=function(q){return function(){app.fetchDescription(q)}}(f);p.innerText="Description";l.appendChild(p);l.setAttribute("data-index",f.index);l.setAttribute("data-length",k.length);l.setAttribute("data-top",
k.top);app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)||l.classList.add("selected");l.style.top=100*l.getAttribute("data-top")+"%";l.style.height=app.hovering.includes(f)?"auto":100*l.getAttribute("data-length")+"%";l.style.minHeight=app.hovering.includes(f)?100*l.getAttribute("data-length")+"%":"auto";!app.closed&&"Manual"==app.mode&&!f.locked&&0>=f.seatsAvailable&&(f=document.createElement("div"),f.className="closedAlign",k=document.createElement("div"),k.className="closedMsg",
k.innerText="CLOSED",f.appendChild(k),l.insertBefore(f,l.childNodes[0]));m.appendChild(l);e.appendChild(m);a.push(l)}}}n=document.getElementById("webWrapper");for(b=document.getElementById("web");b.firstChild;)b.removeChild(b.firstChild);c=Array.isArray(c)?app.webclasses(c):[];n.style.display=c.length?"":"none";for(n=0;n<c.length;++n)if(f=c[n])m=document.createElement("div"),"Automatic"!=app.mode&&app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)||(l=document.createElement("div"),l.className=
"autoLock",l.innerText=f.locked?"\ud83d\udd12":"\ud83d\udd13 ",l.onclick=function(q){return function(u){app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection,!0);q.locked=!q.locked;app.savedCourseGenerator="";app.fillSchedule();null===app.course||app.autoInAlts(app.courses[app.course],q)||(location.hash=app.generateHash(!1))}}(f),m.appendChild(l)),l=document.createElement("div"),l.className="item",p=f.subject+" "+f.courseNumber+"\n"+f.title.replace(/&ndash;/g,
"\u2013")+"\n"+(f.faculty.trim().length?f.faculty+"\n":"")+f.credits+" credit"+(1!=f.credits?"s":"")+"\n",void 0!==f.seatsAvailable&&void 0!==f.maximumEnrollment&&(p+=Math.max(0,f.seatsAvailable)+"/"+f.maximumEnrollment+" seats open\n"),void 0!==f.waitAvailable&&void 0!==f.waitAvailable&&(p+=f.waitAvailable+"/"+f.waitCapacity+" waitlist open\n"),p+=app_config.courseRegistrationCodeName+": "+f.courseRegistrationCode+"\n",l.innerText=p,p=document.createElement("a"),p.className="link",p.onclick=function(q){return function(){app.fetchDescription(q)}}(f),
p.innerText="Description",l.appendChild(p),l.setAttribute("data-index",f.index),app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)||l.classList.add("selected"),m.appendChild(l),!app.closed&&"Manual"==app.mode&&!f.locked&&0>=f.seatsAvailable&&(d=document.createElement("div"),d.className="closedAlign",e=document.createElement("div"),e.className="closedMsg",e.innerText="CLOSED",d.appendChild(e),l.insertBefore(d,l.childNodes[0])),b.appendChild(m),a.push(l);var w=function(q){return function(){for(var u=
0;u<q.length;++u){var r=q[u],t=app.courses[r.getAttribute("data-index")];app.autoInAlts(t,null!==app.course?app.courses[app.course]:null)?r.classList.remove("selected"):r.classList.add("selected");var v=r.parentElement.getElementsByClassName("autoLock");null!==t&&app.hovering.includes(t)?(v.length&&v[0].classList.add("hovering"),r.classList.add("hovering")):(v.length&&v[0].classList.remove("hovering"),r.classList.remove("hovering"));r.getAttribute("data-top")&&(r.style.top=100*r.getAttribute("data-top")+
"%",r.style.height=null!==t&&app.hovering.includes(t)?"auto":100*r.getAttribute("data-length")+"%",r.style.minHeight=null!==t&&app.hovering.includes(t)?100*r.getAttribute("data-length")+"%":"auto")}}}(a);w();for(n=0;n<a.length;++n)a[n].ondblclick=function(q){return function(){app.click(q);app.course=null;document.getElementById("selectBox").value=""}}(app.courses[a[n].getAttribute("data-index")]),a[n].parentElement.onmouseover=function(q){return function(){app.hovering=app.autoAndLabs(q);w()}}(app.courses[a[n].getAttribute("data-index")]),
a[n].parentElement.onmouseout=function(){return function(){app.hovering=[];w()}}();app.dayUpdate();app.autoBar();app.saveMarker();app.updateCredits();document.getElementById("escTip").style.display=null!=app.course?"":"none";window.localStorage.setItem("lastViewed",app.generateHash(!1))};app.disableOnHashChange=!1;
window.onhashchange=function(){app.disableOnHashChange||app.generateHash(!1)==app.getHash().substr(1)||(app.getHash().substr(1).split("=")[0].length?(app.changedTerm("first",{value:app.terms[app.terms.map(function(a){return a.URLcode}).indexOf(app.getHash().split("=")[0].substr(1))].URLcode}),app.updateTerms()):app.clear());app.disableOnHashChange=!1};
app.courseHere=function(a,b,c){if(!c)return null;var d=parseInt(b,10),e=null;c.meetings.forEach(function(g){if("WS"!=g.building&&g.beginTime&&g[a]){var h=app.convertTime(g.beginTime),n=app.convertTime(g.endTime);Math.trunc(h)==d-8&&(e={top:h-Math.trunc(h),length:n-h,loc:g.building&&g.building.trim().length&&g.room&&g.room.trim().length?g.building+" "+g.room:""})}});return e};app.convertTime=function(a){var b=a.substr(-2);return parseFloat(a.substr(0,a.length-b.length))+parseFloat(b)/60-8};
app.webclasses=function(a){return a?a.filter(function(b){return b&&b.meetings.map(function(c){return"ONLINE"==c.building}).reduce(function(c,d){return c||d},!1)}):[]};
app.fetchDescription=function(a){ga("send","event","description","fetch");document.getElementById("description-fetch").style.display="";document.getElementById("description-show").style.display="none";document.getElementById("description").style.display="";document.getElementById("description-strong").innerText=a.subject+" "+a.courseNumber+":";var b=function(c){var d=document.getElementById("description-show");d.innerText=c;d.style.display="";document.getElementById("description-fetch").style.display=
"none"};a.description?b(a.description):(new Searcher("desc",app.term.toString(),a.GETcode.toString())).start(function(c){c=app_config.PROCESSgetDescription(c);b(c);a.description=c})};
app.dayUpdate=function(){if("Automatic"==app.mode)0==app.selected.length||app.courses_generator&&app.courses_generator.data&&app.courses_generator.data[app.course_list_selection]?document.getElementById("noSchedWrapper").style.display="none":document.getElementById("noSchedWrapper").style.display="";else if(document.getElementById("noSchedWrapper").style.display="none","none"==document.getElementById("schedTbody").children[0].children[1].style.display)for(var a=1;5>=a;++a)for(var b=document.getElementById("schedTbody").children,
c=0;c<b.length;++c)b[c].children[a].style.display="";if(0<(null===app.course?app.selected:app.selected.concat(app.courses[app.course])).filter(function(d){return 0<d.meetings.filter(function(e){return e.saturday||e.sunday}).length}).length)for(document.getElementById("schedThead").children[6].style.display="",b=document.getElementById("schedTbody").children,a=0;a<b.length;++a)b[a].children[6].style.display="";else for(document.getElementById("schedThead").children[6].style.display="none",b=document.getElementById("schedTbody").children,
a=0;a<b.length;++a)b[a].children[6].style.display="none";if(0<(null===app.course?app.selected:app.selected.concat(app.courses[app.course])).filter(function(d){return 0<d.meetings.filter(function(e){return e.sunday}).length}).length)for(document.getElementById("schedThead").children[7].style.display="",b=document.getElementById("schedTbody").children,a=0;a<b.length;++a)b[a].children[7].style.display="";else for(document.getElementById("schedThead").children[7].style.display="none",b=document.getElementById("schedTbody").children,
a=0;a<b.length;++a)b[a].children[7].style.display="none"};
app.loadHash=function(a){a=void 0===a?!1:a;if(app.getHash().split("=")[0].length){var b=app.getHash().split("=")[1].split("&")[0].split(",");app.selected=app.courses.filter(function(e){var g=b.map(function(h){return h.replace("!","")}).indexOf(e.URLcode.toString());-1<g&&(e.locked="!"==b[g][b[g].length-1]);return-1<g});document.getElementById("closedCheck").checked=!!app.getHash().split("&")[1];app.closed=!!app.getHash().split("&")[1];if(a){a=[];for(var c=0,d=document.getElementById("saves").children;c<
d.length;++c)JSON.parse(window.localStorage.schedules)[d[c].innerText].split("+")[0]==app.getHash().split("#")[1]&&a.push(d[c]);c=a.filter(function(e){return JSON.parse(window.localStorage.schedules)[e.innerText].split("+")[0]+"?"+e.innerText==window.localStorage.lastSaved});a.length&&((c.length?c[0]:a[0]).classList.add("selected"),app.currentstorage=(c.length?c[0]:a[0]).innerText,document.getElementById("notes").value=JSON.parse(window.localStorage.schedules)[app.currentstorage].split("+")[1])}}else app.clear()};
app.click=function(a){if(null!==a){if(app.autoInAlts(null!==app.course?app.courses[app.course]:null,a))if(ga("send","event","course","add"),document.getElementById("selectBox").value="","Manual"==app.mode)app.course=null,app.selected.push(a);else{var b=app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection).filter(function(d){return app.autoInAlts(null!==app.course?app.courses[app.course]:null,d)});app.course=null;b.forEach(function(d){return app.selected.push(d)});
app.savedCourseGenerator="A";app.autoConstruct(app.selected).get(app.course_list_selection,!0)}else{ga("send","event","course","remove");if("Manual"==app.mode)a.locked=!1,app.selected.splice(app.selected.indexOf(a),1);else{b=app.selected.filter(function(d){return a.home==d.home});for(var c=0;c<b.length;++c)b[c].locked=!1;app.selected=app.selected.filter(function(d){return a.home!=d.home})}app.hovering=[]}location.hash=app.generateHash(!1);app.course_list_selection=0;b=document.getElementById("Range");
b.max=0;b.value=0;app.hideSearch();app.fillSchedule()}};app.totalCredits=function(){return app.selected.reduce(function(a,b){return a+b.credits},0)};app.updateCredits=function(){document.getElementById("credits").innerText=app.totalCredits()};
app.autoBar=function(){var a=document.getElementById("autoBar");a.style.display="Automatic"==app.mode&&(0<app.selected.length||null!==app.course)&&app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(1,!1)?"block":"none";document.getElementById("nextButton").innerText="Next";"none"==a.style.display?(document.getElementById("selectBox").size=25,document.getElementById("Automatic").style.marginBottom="10px"):(document.getElementById("selectBox").size=24,document.getElementById("Automatic").style.marginBottom=
"0px")};
app.genNext=function(a){if(a){app.courses_generator&&app.courses_generator.get(app.courses_generator.data?app.courses_generator.data.length:0)?app.course_list_selection=(app.courses_generator.data?app.courses_generator.data.length:0)-1:(app.course_list_selection++,app.course_list_selection%=app.courses_generator?app.courses_generator.data.length:0);app.fillSchedule();var b=document.getElementById("Range");b.max=app.courses_generator?app.courses_generator.data.length-1:0;b.value=app.course_list_selection;a.innerText=
app.courses_generator&&app.courses_generator.done?"Loop":"Next"}};
app.changedTerm=function(a,b){a=void 0===a?!1:a;b=void 0===b?null:b;a||null===b||!app.changed()||window.confirm("Are you sure you want to discard your changes?")?1==a||app.clear(!a&&null!==b&&app.changed(),"first"==a)?(b&&(b.firstChild&&""==b.firstChild.value&&b.removeChild(b.firstChild),app.term=b.value),app.term&&(app.course=null,document.getElementById("selectBox").value="",document.getElementById("searchBox").value="",app.selected=[],app.course_list_selection=0,b=document.getElementById("Range"),
b.max=0,b.value=0,app.courses_generator=null,app.savedCourseGenerator="","first"!=a&&app.fillSchedule(),app.percent="",document.getElementById("coursesBox").style.display="none",document.getElementById("loadingCourses").style.display="",app.termCacher.push(app.term,function(c){return function(d){app.courses=d;app.genDivs();app.fillSchedule();app.fillSearch();app.loadHash("first"==c);d=document.getElementById("notes");null!==d&&app.updateNotes(d)}}(a)))):document.getElementById("termSelect").value=
app.term:document.getElementById("termSelect").value=app.term};
app.genDivs=function(a){app.courses_manual="";for(a=0;a<app.courses.length;a++)app.courses_manual+='<option value="'+app.courses[a].index+'">'+app.courses[a].subject+" "+app.courses[a].courseNumber+(app.courses[a].sessionMod?app.courses[a].sessionMod:"")+": "+app.courses[a].title+"</option>";app.courses_auto="";for(a=0;a<app.courses.length;++a)if(0==a||app.courses[a].subject+app.courses[a].courseNumber!=app.courses[a-1].subject+app.courses[a-1].courseNumber)app.courses_auto+='<option value="'+app.courses[a].index+
'">'+app.courses[a].subject+" "+app.courses[a].courseNumber+": "+app.courses[a].title+"</option>";document.getElementById("coursesBox").style.display="";document.getElementById("loadingCourses").style.display="none"};app.updateTerms=function(){for(var a=document.getElementById("termSelect");a.lastChild;)a.removeChild(a.lastChild);for(var b=0;b<app.terms.length;b++){var c=app.terms[b],d=document.createElement("option");d.value=c.URLcode;d.innerText=c.title;a.appendChild(d)}a.value=app.term};
app.updatePercent=function(){document.getElementById("loadingCourses").innerText="Loading Courses... "+app.percent};app.updateNotes=function(a){a&&a.style.height!=a.scrollHeight+25+"px"&&(a.style.height="25px",a.style.height=a.scrollHeight+25+"px",app.saveMarker())};app.fillSearch=function(a){a=void 0===a?null:a;var b=document.getElementById("selectBox"),c=b.value;b.innerHTML=app.autoFilter(a);b.value=c;app.hideSearch()};
app.autoFilter=function(a){app.mode=a?a.value:app.mode;return"Manual"==app.mode?app.courses_manual:app.courses_auto};app.hideSearch=function(a){if(a=void 0===a?null:a)app.closed=a.checked,location.hash=app.generateHash(!1);a=document.getElementById("selectBox").children;for(var b=document.getElementById("searchBox").value.toLowerCase(),c=0;c<a.length;++c)a[c].value&&(a[c].style.display=app.filterSearch(app.courses[a[c].value],b)?"":"none")};
app.filterSearch=function(a,b){return null===a||-1!==app.selected.indexOf(a)||!app.closed&&("Manual"==app.mode?0>=a.seatsAvailable:a.home.alts.map(function(c){return c.map(function(d){return 0>=d.seatsAvailable}).reduce(function(d,e){return d&&e},!0)}).reduce(function(c,d){return c||d},!1))||b&&!(-1<(a.subject+" "+a.courseNumber).toLowerCase().indexOf(b)||-1<a.title.toLowerCase().indexOf(b)||a.URLcode.toString()==b)||"Automatic"==app.mode&&a.home.alts.reduce(function(c,d){return c.concat(d)},[]).some(function(c){return app.selected.includes(c)})?
!1:!0};var animator={element:void 0,down:function(a){return function(b){window.addEventListener("selectstart",animator.disableSelect);animator.element=a;animator.element.style.position="relative";animator.startX=b.clientX;animator.startY=b.clientY;animator.startCenterX=animator.element.offsetLeft+animator.element.offsetWidth/2;animator.startCenterY=animator.element.offsetTop+animator.element.offsetHeight/2}},move:function(a){if(void 0!==animator.element){animator.element.style.top=(a.clientY-animator.startY).toString()+
"px";animator.element.style.left=(a.clientX-animator.startX).toString()+"px";var b=animator.element.offsetLeft+animator.element.offsetWidth/2;animator.element.nextSibling&&b>animator.element.nextSibling.offsetLeft+animator.element.nextSibling.offsetWidth/2&&(animator.element.parentNode.insertBefore(animator.element.nextSibling,animator.element),animator.startX+=b-animator.startCenterX,animator.startCenterX=b,animator.element.style.left=(a.clientX-animator.startX).toString()+"px");animator.element.previousSibling&&
b<animator.element.previousSibling.offsetLeft+animator.element.previousSibling.offsetWidth/2&&(animator.element.parentNode.insertBefore(animator.element,animator.element.previousSibling),animator.startX+=b-animator.startCenterX,animator.startCenterX=b,animator.element.style.left=(a.clientX-animator.startX).toString()+"px")}},up:function(a){if(void 0!==animator.element){window.removeEventListener("selectstart",animator.disableSelect);animator.element.style.top="auto";animator.element.style.left="auto";
animator.element.style.position="static";if(5<Math.abs(a.clientX-animator.startX)||5<Math.abs(a.clientY-animator.startY)){var b=document.getElementById("saves").children,c=[];for(a=0;a<b.length;++a)c.push([b[a].innerText,JSON.parse(window.localStorage.schedules)[b[a].innerText]]);b={};for(a=0;a<c.length;++a)b[c[a][0]]=c[a][1];window.localStorage.schedules=JSON.stringify(b)}else{c=animator.element.parentElement;for(a=0;a<c.children.length;++a)c.children[a].classList.remove("preselect");animator.element.classList.add("preselect");
b=app.load(animator.element.innerText);for(a=0;a<c.children.length;++a)c.children[a].classList.remove("preselect");if(b){for(a=0;a<c.children.length;++a)c.children[a].classList.remove("selected");animator.element.classList.add("selected");app.saveMarker()}}animator.element=void 0}},disableSelect:function(a){a.preventDefault()}};window.onmouseup=animator.up;window.onmousemove=animator.move;
app.saveMarker=function(){document.getElementById("marker-save").style.display=app.changed()&&app.selected.length?"":"none";document.getElementById("marker-discard").style.display=app.changed()&&app.currentstorage&&app.selected.length?"":"none";document.getElementById("marker-saveAsNew").style.display=app.currentstorage?"":"none";document.getElementById("marker-delete").style.display=app.currentstorage?"":"none";document.getElementById("marker-export").style.display=app.selected.length?"":"none";
document.getElementById("marker-new").style.display=app.currentstorage||app.selected.length?"":"none"};
app.updateSaved=function(){var a=Object.keys(JSON.parse(window.localStorage.schedules));if(a.length){for(var b=document.getElementById("saves"),c=0;c<b.children.length;++c){var d=b.children[c],e=a.findIndex(function(g){return g==d.innerText});-1==e?(b.removeChild(d),--c):a.splice(e,1)}for(c=0;c<a.length;++c)e=document.createElement("div"),e.className="option draggable",e.innerText=a[c],b.appendChild(e);a=b.children;for(c=0;c<a.length;++c)a[c].onmousedown=animator.down(a[c]);for(c=0;c<a.length;++c)b=
a[c],app.currentstorage==b.innerText?b.classList.add("selected"):b.classList.remove("selected");app.saveMarker()}};
app.save=function(){if(!app.currentstorage){var a=window.prompt("Please enter a name for the schedule");if(!a)return;app.currentstorage=a}window.localStorage.schedules||window.localStorage.setItem("schedules","{}");a=JSON.parse(window.localStorage.schedules);a[app.currentstorage]=app.generateHash(!0);window.localStorage.setItem("schedules",JSON.stringify(a));window.localStorage.setItem("lastSaved",app.generateHash(!1)+"?"+app.currentstorage);app.selected=[];app.course_list_selection=0;a=document.getElementById("Range");
a.max=0;a.value=0;app.courses_generator=null;app.savedCourseGenerator="";app.loadHash();app.autoBar();app.updateSaved()};
app.load=function(a){if(null===a||app.changed()&&!window.confirm("Are you sure you want to discard your changes?"))return!1;ga("send","event","schedule","load");app.currentstorage=a;document.getElementById("notes").value=JSON.parse(window.localStorage.schedules)[a].split("+")[1];app.disableOnHashChange=!0;location.hash=JSON.parse(window.localStorage.schedules)[a].split("+")[0];a=app.getHash().split("=")[0].substr(1);a=app.terms.map(function(b){return b.URLcode}).indexOf(a);-1<a&&(app.term!=app.terms[a].URLcode?
app.term=app.terms[a].URLcode:(app.course=null,document.getElementById("selectBox").value=""),app.updateTerms(),app.changedTerm(!0));app.updateNotes(document.getElementById("notes"));app.fillSchedule();window.localStorage.setItem("lastSaved",app.generateHash(!1)+"?"+app.currentstorage);return!0};app.discard=function(){var a=app.currentstorage;app.currentstorage=null;app.changed()&&!app.load(a)?app.currentstorage=a:(ga("send","event","schedule","discard"),window.localStorage.setItem("lastSaved","{}"))};
app.saveNew=function(){ga("send","event","schedule","save-new");app.currentstorage=null;app.save()};app.deleteSchedule=function(){if(window.confirm("Are you sure you want to delete the schedule "+app.currentstorage+"?")){var a=JSON.parse(window.localStorage.schedules);delete a[app.currentstorage];window.localStorage.setItem("schedules",JSON.stringify(a));app.clear(!0);app.updateSaved();app.fillSchedule();window.localStorage.setItem("lastSaved","{}")}};
app.clear=function(a,b){b=void 0===b?!1:b;if((void 0===a||!a)&&app.changed()&&!window.confirm("Are you sure you want to discard your changes?"))return location.hash=app.generateHash(!1),!1;ga("send","event","schedule","new");document.getElementById("selectBox").value="";app.course_list_selection=0;a=document.getElementById("Range");a.max=0;a.value=0;app.courses_generator=null;app.savedCourseGenerator="";b||(location.hash="");document.getElementById("notes").value="";app.course=null;app.selected=[];
app.currentstorage=null;app.updateSaved();app.fillSchedule();app.hideSearch();window.localStorage.setItem("lastSaved","{}");return!0};app.showExport=function(){document.getElementById("export").style.display="";document.getElementById("export-link").value=location.href;document.getElementById("export-text").value=app.selected.map(function(a){return a.courseRegistrationCode+": "+a.subject+" "+a.courseNumber}).join("\n")};var Lazy=function(a){this.core=a;this.data=[];this.filters=[];this.done=!1};
Lazy.prototype.get=function(a,b){b=void 0===b?!1:b;if(Array.isArray(this.core))return this.core;for(;!this.done&&this.data.length<=a;){var c=this.core.next();if(c.done){this.done=!0;break}this.filters.reduce(function(d,e){return d&&e(c.value)},!0)&&this.data.push({value:c.value,selected:c.value.filter(function(d){return!d.home.alts.reduce(function(e,g){return e.concat(g)},[]).includes(null!==app.course?app.courses[app.course]:null)})})}a=this.data[a];if(!a)return!1;b&&(app.selected=a.selected);location.hash=
app.generateHash(!1);return a.value};Lazy.prototype.filter=function(a){this.filters.push(a);return this};
app.autoConstruct=function(a,b){b=void 0===b?!1:b;if(void 0===a[0]||null===a[0])return new Lazy([]);void 0!==a.slice(-1)[0]&&null!==a.slice(-1)[0]||a.pop();if("Manual"==app.mode){a=app.closed||b?a:a.filter(function(c){return 0<c.seatsAvailable||c.locked});if("M"+a.map(function(c){return c.URLcode}).join()==app.savedCourseGenerator)return app.courses_generator||new Lazy([]);"A"==app.savedCourseGenerator[0]&&null!=app.course&&(app.courses_generator&&app.courses_generator.get(app.course_list_selection)&&
(b=app.courses_generator.get(app.course_list_selection),a=Array.isArray(b)?b:[]),app.course=a.filter(function(c){return null!==app.course&&c.home==app.courses[app.course].home})[0].index,document.getElementById("selectBox").value=app.course.toString());app.savedCourseGenerator="M"+a.map(function(c){return c.URLcode}).join();app.courses_generator=new Lazy(a);return app.courses_generator}if("A"+app.removeDuplicatesBy(function(c){return c.home},a).map(function(c){return c.home.URLcode}).filter(function(c){return c}).join()+
(app.closed?"C":"")==app.savedCourseGenerator)return app.courses_generator||new Lazy([]);"M"==app.savedCourseGenerator[0]&&app.course&&(app.course=app.courses[app.course].home.index,document.getElementById("selectBox").value=app.course.toString());app.course_list_selection=0;b=document.getElementById("Range");b.max=0;b.value=0;app.courses_generator=(new Lazy(app.cartesianProduct(app.removeDuplicatesBy(function(c){return c.home},a).reduce(function(c,d){d.home.alts.forEach(function(e){var g=e.filter(function(h){return h.locked});
g.length?e=g:a.forEach(function(h){e.includes(h)&&(e=e.filter(function(n){return n!=h}),e.unshift(h))});c.push(app.closed?e:e.filter(function(h){return 0<h.seatsAvailable||h.locked}))});return c},[])))).filter(app.schedCompat);app.savedCourseGenerator="A"+app.removeDuplicatesBy(function(c){return c.home},a).map(function(c){return c.home.URLcode}).filter(function(c){return c}).join()+(app.closed?"C":"");return app.courses_generator};
app.removeDuplicatesBy=function(a,b){var c=new Set;return b.filter(function(d){d=a(d);var e=!c.has(d);e&&c.add(d);return e})};
app.cartesianProduct=function $jscomp$generator$function(a){var c,d,e;return $jscomp.generator.createGenerator($jscomp$generator$function,function(g){switch(g.nextAddress){case 1:if(a.map(function(h){return 0==h.length}).reduce(function(h,n){return h||n},!1))return g.return();if(!(1>=a.length)){g.jumpTo(2);break}c=0;case 3:if(!(c<a[0].length)){g.jumpTo(5);break}return g.yield([a[0][c]],4);case 4:++c;g.jumpTo(3);break;case 5:return g.return();case 2:d=Array(a.length).fill(0,0,a.length);case 7:for(c=
0;c<d.length-1;++c)d[c]>a[c].length-1&&(d[c]=0,d[c+1]++);if(d[d.length-1]>a[a.length-1].length-1)return g.return();e=Array(a.length-1);for(c=0;c<a.length;++c)e[c]=a[c][d[c]];return g.yield(e,9);case 9:d[0]++,g.jumpTo(7)}})};app.schedCompat=function(a){if(1==a.length)return!0;for(var b=[a[0]],c=1;c<a.length;){for(var d=0;d<b.length;++d)if(!app.courseCompat(b[d],a[c]))return!1;b.push(a[c++])}return!0};
app.courseCompat=function(a,b){return a.meetings.reduce(function(c,d){return c&&b.meetings.reduce(function(e,g){return e&&app.meetingCompat(d,g)},!0)},!0)};app.meetingCompat=function(a,b){return"monday tuesday wednesday thursday friday saturday sunday".split(" ").reduce(function(c,d){return c||a[d]&&b[d]},!1)?!(a.beginTime>=b.beginTime&&a.beginTime<b.endTime||a.endTime>b.beginTime&&a.endTime<=b.endTime||b.endTime>a.beginTime&&b.endTime<=a.endTime||b.endTime>a.beginTime&&b.endTime<=a.endTime):!0};window.onload=function(){void 0==window.localStorage.lastSaved&&(window.localStorage.lastSaved="");void 0==window.localStorage.schedules&&(window.localStorage.schedules="{}");void 0==window.localStorage.darkMode&&(window.localStorage.darkMode="false");void 0==window.localStorage.darkMode&&(window.localStorage.darkMode="false");var a=document.getElementById("styleSlider");a.checked="true"==window.localStorage.darkMode;change_style(a);app.mode=document.getElementById("Manual").checked?"Manual":"Automatic";
app.closed=!!app.getHash().split("&")[1];document.getElementById("closedCheck").checked=app.closed;app_config.CORStest?(new Searcher("test")).start(function(d){d?(document.getElementById("loading").style.display="none",document.getElementById("main").style.display=""):(document.getElementById("loading").style.display="none",document.getElementById("cors").style.display="")}):(document.getElementById("loading").style.display="none",document.getElementById("main").style.display="");(new Searcher("terms")).start(function(d){app.terms=
app_config.PROCESSgetTerms(d);d=(app.getHash().split("=")[1]||"").split("&")[0].length?app.terms.map(function(e){return e.URLcode}).indexOf(app.getHash().split("=")[0].substr(1)):-1;(app.getHash().split("=")[1]||"").split("&")[0].length&&-1<d?(app.term=app.terms[d].URLcode,app.updateTerms(),app.changedTerm("first")):(app.term=app.terms[0].URLcode,app.updateTerms(),app.changedTerm(!1));document.getElementById("termSelect").value=app.term;app.updateSaved()});var b=document.getElementById("nextButton"),
c={waiter:null,advanceNextButton:function(d){app.genNext(b);c.waiter=setTimeout(c.advanceNextButton,1)},pressingDown:function(d){app.genNext(b);c.waiter=setTimeout(c.advanceNextButton,750)},notPressingDown:function(d){clearTimeout(c.waiter);c.waiter=null}};b.addEventListener("mousedown",c.pressingDown,!1);b.addEventListener("mouseup",c.notPressingDown,!1);b.addEventListener("mouseleave",c.notPressingDown,!1);b.addEventListener("touchstart",c.pressingDown,!1);b.addEventListener("touchend",c.notPressingDown,
!1);(function(){var d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src="//www.heeduser.com/supfiles/Script/widget.js";var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e)})();document.getElementById("feedback").innerHTML='<a id="heeduser_wb" href="JavaScript:heeduser_openwidget(heeduser_url,\''+_heeduser.widget_layout+"')\">Leave your feedback!</a>"};
var _heeduser={type:"button",community:"sitscheduler",url:"http://sitscheduler.heeduser.com",placement:"middle-right",color:"#202021",widget_layout:"full",sso_token:""},heeduser_url=_heeduser.url+"/FeedbackWidget/Widget.aspx?sso_token="+encodeURIComponent(_heeduser.sso_token);
